<!-- span content -->
<div class="span9">
    <!-- content -->
    <div class="content">
	
	
	<!-- content-breadcrumb -->
	<div class="content-breadcrumb">
	    
	    
	    <!--breadcrumb-->
	    <ul class="breadcrumb">
		<li><a href="../system/dashboard"><i class="icofont-home"></i>主面板</a> <span class="divider">&rsaquo;</span></li>
		<!--li><a href="form.html">个人设置</a> <span class="divider">&rsaquo;</span></li-->
		<li class="active">修改密码</li>
	    </ul><!--/breadcrumb-->
	</div><!-- /content-breadcrumb -->
	
	<!-- content-body -->
	<div class="content-body">
	    <!-- form -->
	    <div class="row-fluid">
		<div class="span12">
		    
		    <!-- =========================================
					ELEMENT
		    =========================================== -->
		    <!--element-->
		    <div id="element" class="row-fluid">
			<!--span-->
			<div class="span12">
			    <!--box-->
			    <div class="box corner-all">
				<!--box header-->
				<div class="box-header grd-white color-silver-dark corner-top">
				    <!--div class="header-control">
					<a data-box="collapse"><i class="icofont-caret-up"></i></a>
					<a data-box="close">&times;</a>
				    </div-->
				    <span>修改密码</span>
				</div><!--/box header-->
				<!--box body-->
				<div class="box-body">
				    <!--element-->
				    <form class="form-horizontal" />
					
					<div class="control-group">
					    <label class="control-label" for="inputAuto">原始密码</label>
					    <div class="controls">
						<input type="password" id="oldpasswd" class="grd-white" />
					    </div>
					</div>
					<div class="control-group">
					    <label class="control-label" for="inputAuto">新密码</label>
					    <div class="controls">
						<input type="password" id="passwd" class="grd-white" />
					    </div>
					</div>
					<div class="control-group">
					    <label class="control-label" for="inputAuto">重新输入</label>
					    <div class="controls">
						<input type="password" id="repasswd" class="grd-white" />
					    </div>
					</div>
					<div class="form-actions">
					    <button type="button" class="btn btn-primary" id="save">保存</button>
					</div>
				    </form>
				    <!--/element-->
				</div><!--/box body-->
			    </div><!--/box-->
			</div><!--/span--> 
		    </div><!--/element-->
		    
		</div><!--/span-->
	    </div><!--/row-fluid-->
	    <!--/form-->
	</div><!--/content-body -->
    </div><!-- /content -->
</div><!-- /span content -->