<!-- span content -->
<div class="span9">
    <!-- content -->
    <div class="content">
	
	
	<!-- content-breadcrumb -->
	<div class="content-breadcrumb">
	    
	    
	    <!--breadcrumb-->
	    <ul class="breadcrumb">
		<li><a href="../system/dashboard"><i class="icofont-home"></i>主面板</a> <span class="divider">&rsaquo;</span></li>
		<!--li><a href="javascript:;">个人设置</a> <span class="divider">&rsaquo;</span></li-->
		<li class="active">修改信息</li>
	    </ul><!--/breadcrumb-->
	</div><!-- /content-breadcrumb -->
	
	<!-- content-body -->
	<div class="content-body">
	    <!-- form -->
	    <div class="row-fluid">
		<div class="span12">
		    
		    <!-- =========================================
					ELEMENT
		    =========================================== -->
		    <!--element-->
		    <div id="element" class="row-fluid">
			<!--span-->
			<div class="span12">
			    <!--box-->
			    <div class="box corner-all">
				<!--box header-->
				<div class="box-header grd-white color-silver-dark corner-top">
				    <!--div class="header-control">
					<a data-box="collapse"><i class="icofont-caret-up"></i></a>
					<a data-box="close">&times;</a>
				    </div-->
				    <span>信息设置</span>
				</div><!--/box header-->
				<!--box body-->
				<div class="box-body">
				    <!--element-->
				    <form class="form-horizontal" id="profile_form"/>
					<div class="control-group">
					    <label class="control-label" for="inputAuto">E-mail：</label>
					    <div class="controls">
						<input type="email" name="" readonly='true' class="grd-white" value="<?=$user['email']?>"/>
					    </div>
					</div>
					<div class="control-group">
					    <label class="control-label" for="inputAuto">部门：</label>
					    <div class="controls">
						<input type="text" readonly='true' class="grd-white" value="<?=$user['department']?>"/>
					    </div>
					</div>
					<div class="control-group">
					    <label class="control-label" for="inputAuto">真实姓名：</label>
					    <div class="controls">
						<input type="text" name="name" class="grd-white" value="<?=$user['name']?>"/>
					    </div>
					</div>
					<div class="control-group">
					    <label class="control-label" for="inputSelect">性别：</label>
					    <div class="controls">
						<select name="sex" data-form="select2" style="width:200px">
						    <option value=1 <?php if($user['sex'] == 1){?> selected="selected" <?php } ?> >男</option>
						    <option value=0 <?php if($user['sex'] == 0){?> selected="selected" <?php } ?> >女</option>
						</select>
					    </div>
					</div>
					<!--div class="control-group">
					    <label class="control-label" for="inputAuto">职务：</label>
					    <div class="controls">
						<input type="text" id="" class="grd-white" />
					    </div>
					</div-->
					<div class="control-group">
					    <label class="control-label" for="inputAuto">工位：</label>
					    <div class="controls">
						<input type="text" name="position" class="grd-white"  value="<?=$user['position']?>"/>
					    </div>
					</div>
					<div class="control-group">
					    <label class="control-label" for="inputAuto">工号：</label>
					    <div class="controls">
						<input type="text" name="employeeid" class="grd-white" value="<?=$user['employeeid']?>"/>
					    </div>
					</div>
					<div class="control-group">
					    <label class="control-label" for="inputAuto">办公电话：</label>
					    <div class="controls">
						<input type="text" name="telephone" class="grd-white"  value="<?=$user['telephone']?>"/>
					    </div>
					</div>
					<div class="control-group">
					    <label class="control-label" for="inputAuto">移动电话：</label>
					    <div class="controls">
						<input type="text" name="cellphone" class="grd-white" value="<?=$user['cellphone']?>" />
					    </div>
					</div>
					<div class="control-group">
					    <label class="control-label" for="inputUpload">上传头像：</label>
					    <div class="controls">
						<input type="file" data-form="uniform" id="photo" />
					    </div>
					    <div class="controls" style="margin-top:20px;">
						<img src="/profile/photoView/?path=<?=$user['photo']?>"  width="48" height="48" id="img_photo"/>
						<input type="hidden" name="photo" value="<?=$user['photo']?>"/>
					    </div>
					</div>
					<div class="control-group">
					    <label class="control-label" for="inputDate">生日：</label>
					    <div class="controls">
						<div class="input-append date" data-form="datepicker" data-date="<?=$user['birthdate']?>" data-date-format="yyyy-mm-dd">
						    <input name="birthdate" class="grd-white" size="16" type="text" value="<?=$user['birthdate']?>" readonly="true">
						    <span class="add-on"><i class="icon-th"></i></span>
						</div>
					    </div>
					</div>
					<!--div class="control-group">
					    <label class="control-label" for="inputSelect">所属公司：</label>
					    <div class="controls">
						<select id="inputSelect" data-form="select2" style="width:200px" data-placeholder="Your Favorite Type of Bear">
						    <option />北京
						    <option />上海
						</select>
					    </div>
					</div-->
					<div class="form-actions">
					    <button type="button" id="save" class="btn btn-primary">保存</button>
					</div>
				    </form>
				    <!--/element-->
				</div><!--/box body-->
			    </div><!--/box-->
			</div><!--/span--> 
		    </div><!--/element-->
		    
		</div><!--/span-->
	    </div><!--/row-fluid-->
	    <!--/form-->
	</div><!--/content-body -->
    </div><!-- /content -->
</div><!-- /span content -->