
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>Request Not Found - Stilearn Admin Bootstrap</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="" />
        <meta name="author" content="stilearning" />
        <!-- styles -->
        <link href="/public/css/bootstrap.css" rel="stylesheet" />
        <link href="/public/css/bootstrap-responsive.css" rel="stylesheet" />
        <link href="/public/css/stilearn.css" rel="stylesheet" />
        <link href="/public/css/stilearn-responsive.css" rel="stylesheet" />
        <link href="/public/css/stilearn-helper.css" rel="stylesheet" />
        <link href="/public/css/stilearn-icon.css" rel="stylesheet" />
        <link href="/public/css/font-awesome.css" rel="stylesheet" />
        <link href="/public/css/animate.css" rel="stylesheet" />
        
        <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
        <!--[if lt IE 9]>
          <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" /></head>

    <body>
        <!-- section header -->
        <header class="header" data-spy="affix" data-offset-top="0">
            <!--nav bar helper-->
            <div class="navbar-helper">
                <div class="row-fluid">
                    <!--panel site-name-->
                    <div class="span2">
                        <div class="panel-sitename">
                          <h2><a href="/system/dashboard"><span class="color-teal">石</span>Stone</a></h2>
                        </div>
                    </div>
                    <!--/panel name-->
                </div>
            </div><!--/nav bar helper-->
        </header>
        
        <!-- section content -->
        <section class="section">
            <div class="container">
                <div class="error-page">
                    <h1 class="error-code color-red">Error 404</h1>
                    <p class="error-description muted">抱歉! 找不到请求的页面</p>
                    <form />
                        <div class="control-group">
                            <div class="input-append input-icon-prepend">
                                <div class="add-on">
                                    <a title="search" style="" class="icon"><i class="icofont-search"></i></a>
                                    <input class="input-xxlarge animated grd-white" type="text" placeholder="搜索本地内容" />
                                </div>
                                <input type="submit" class="btn" value="搜索" />
                            </div>
                        </div>
                    </form>
                    <a href="/dashboard" class="btn btn-small btn-primary"><i class="icofont-arrow-left"></i> 回到快捷面板</a>
                    <a href="/system" target="_blank" class="btn btn-small btn-success">回到管理系统 <i class="icofont-arrow-right"></i></a>
                </div>
            </div>
        </section>

        <!-- section footer -->
        <footer>
            <a rel="to-top" href="#top"><i class="icofont-circle-arrow-up"></i></a>
        </footer>
    </body>
</html>