<!-- span content -->
<div class="span9">
<!-- content -->
<div class="content">
	<!-- content-header 
	<div class="content-header">
		<ul class="content-header-action pull-right">
			<li>
				<a href="#">
					<div class="badge-circle grd-green color-white"><i class="icofont-plus-sign"></i></div>
					<div class="action-text color-green">8765 <span class="helper-font-small color-silver-dark">Visits</span></div>
				</a>
			</li>
			<li class="divider"></li>
			<li>
				<a href="#">
					<div class="badge-circle grd-teal color-white"><i class="icofont-user-md"></i></div>
					<div class="action-text color-teal">1437 <span class="helper-font-small color-silver-dark">Users</span></div>
				</a>
			</li>
			<li class="divider"></li>
			<li>
				<a href="#">
					<div class="badge-circle grd-orange color-white">$</div>
					<div class="action-text color-orange">4367 <span class="helper-font-small color-silver-dark">Orders</span></div>
				</a>
			</li>
		</ul>
		<h2><i class="icofont-calendar"></i> 考勤维护</h2>
	</div> /content-header -->
	
	<!-- content-breadcrumb -->
	<div class="content-breadcrumb">
		<!--breadcrumb-nav
		<ul class="breadcrumb-nav pull-right">
			<li class="divider"></li>
			<li class="btn-group">
				<a href="#" class="btn btn-small btn-link">
					<i class="icofont-money"></i> Orders <span class="color-red">(+12)</span>
				</a>
			</li>
			<li class="divider"></li>
			<li class="btn-group">
				<a href="#" class="btn btn-small btn-link">
					<i class="icofont-user"></i> Users <span class="color-red">(+34)</span>
				</a>
			</li>
			<li class="divider"></li>
			<li class="btn-group">
				<a href="#" class="btn btn-small btn-link dropdown-toggle" data-toggle="dropdown">
					<i class="icofont-tasks"></i> Tasks
					<i class="icofont-caret-down"></i>
				</a>
				<ul class="dropdown-menu">
					<li><a href="#">Some Action</a></li>
					<li><a href="#">Other Action</a></li>
					<li class="divider"></li>
					<li><a href="#">Something Else</a></li>
				</ul>
			</li>
		</ul>/breadcrumb-nav-->
		
		<!--breadcrumb-->
		<ul class="breadcrumb">
			<li><a href="../system/dashboard"><i class="icofont-home"></i> 主面板</a> <span class="divider">&rsaquo;</span></li>
			<li><a href="index">考勤管理</a> <span class="divider">&rsaquo;</span></li>
			<li class="active">考勤设置</li>
		</ul><!--/breadcrumb-->
	</div><!-- /content-breadcrumb -->
	
	<!-- content-body -->
	<div class="content-body">
		<!-- calendar -->
		<div class="row-fluid">
			<div class="span9">
				<div class="box corner-all">
					<div class="box-header grd-white corner-top">
						<span>考勤设置</span>
					</div>
					<div class="box-body">
						<div id="calendar"></div>
					</div>
				</div>
			</div>
			<div class="span3">
				<div class="box corner-all" id="atten-setting">
					<div class="box-header grd-white corner-top">
						<span>设置</span>
					</div>
					<div class="box-body">						
					    <p><span>默认休息日</span></p>
                                            <p><input type="hidden" id="inputTags" value="6,0" /></p>
					    <p><span>上班时间</span></p>
					    <p><input type="text" id="dutytime" class="grd-white" value="09:00-18:00"></p>
					    <p><span>特殊设置</span></p>
					    <p><button type="button" class="btn btn-info" id="btn-workday">工作日</button>&nbsp;&nbsp;&nbsp;<button type="button" class="btn btn-success"  id="btn-holiday">休息日</button></p>
					    <p><button type="button" class="btn btn-primary" id="btn-atten-setting">提交</button></p>
					</div>
				</div>
			</div>
		</div>
		<!--/calendar-->
	</div><!--/content-body -->
</div><!-- /content -->
</div>
<!-- /span content -->