<footer>
    <a rel="to-top" href="#top"><i class="icofont-circle-arrow-up"></i></a>
</footer>
<?php foreach ($scripts as $script):?>
    <script src="<?=$script?>"></script>
<?php endforeach;?>
<?php foreach ($local_scripts as $script):?>
    <script src="<?=$script?>"></script>
<?php endforeach;?>

<!-- 审批，添加分类 -->
<div id="approve_new_type" class="modal fade hide" tabindex="-1" role="dialog" aria-labelledby="modal-recoverLabel" aria-hidden="true">
	<div class="modal-header">
	    <button type="button" class="close" data-dismiss="modal" aria-hidden="true" node-act="close" >&times;</button>
	    <h4 id="modal-recoverLabel">新建分类名称</h4>
	</div>
	<div class="modal-body">
	    <form id="form-recover" method="post" />
		<div class="control-group">
		    <div class="controls">
			<input type="text" name="approvetypename" />
			<p class="help-block helper-font-small">请输入分类名称</p>
		    </div>
		</div>
	    </form>
	</div>
	<div class="modal-footer">
	    <input type="button" form="form-recover" class="btn btn-primary" value="保存" node-act="sure" />
	    <button class="btn" data-dismiss="modal" aria-hidden="true" node-act="cancel" >取消</button>
	</div>
</div>
<!-- /审批，添加分类-->

<!-- 文件，创建文件夹 -->
<div id="layer-create-folder" class="modal fade hide" tabindex="-1" role="dialog" aria-labelledby="modal-recoverLabel" aria-hidden="true">
	<div class="modal-header">
	    <button type="button" class="close" data-dismiss="modal" aria-hidden="true" node-act="close" >&times;</button>
	    <h4 id="modal-recoverLabel">创建文件夹</h4>
	</div>
	<div class="modal-body">
	    <form id="form-recover" method="post" />
		<div class="control-group">
		    <div class="controls">
			<input type="text" name="newname" />
			<p class="help-block helper-font-small">请输入名称</p>
		    </div>
		</div>
	    </form>
	</div>
	<div class="modal-footer">
	    <span style="color:#b94a48;" node-id="message"></span>
	    <input type="button" form="form-recover" class="btn btn-primary" value="保存" node-act="sure" />
	    <button class="btn" data-dismiss="modal" aria-hidden="true" node-act="cancel" >取消</button>
	</div>
</div>
<!-- /文件，创建文件夹 -->

<!-- 重命名 -->
<div id="layer_rename" class="modal fade hide" tabindex="-1" role="dialog" aria-labelledby="modal-recoverLabel" aria-hidden="true">
	<div class="modal-header">
	    <button type="button" class="close" data-dismiss="modal" aria-hidden="true" node-act="close">&times;</button>
	    <h4 id="modal-recoverLabel">编辑</h4>
	</div>
	<div class="modal-body">
	    <form id="form-recover" method="post" />
		<div class="control-group">
		    <div class="controls">
			<input type="text" name="rename" />
			<p class="help-block helper-font-small">请输入新名称</p>
		    </div>
		</div>
	    </form>
	</div>
	<div class="modal-footer">
	    <input type="button" form="form-recover" class="btn btn-primary" value="保存" node-act="sure" />
	    <input type="button" form="form-recover" class="btn btn-primary" value="删除" node-act="del" />
	    <button class="btn" data-dismiss="modal" aria-hidden="true" node-act="cancel" >取消</button>
	</div>
</div>
<!-- /重命名-->

<!-- 审批，报表字段-- -->
<div id="approveLayer1" class="modal fade hide" tabindex="-1" role="dialog" aria-labelledby="modal-recoverLabel" aria-hidden="true">
	<div class="modal-header">
	    <button type="button" class="close" data-dismiss="modal" aria-hidden="true" node-act="close">&times;</button>
	    <h4 id="modal-recoverLabel">添加字段名</h4>
	</div>
	<div class="modal-body">
	    <form id="form-recover" method="post" />
		<div class="control-group">
		    <label class="control-label" for="approveInputName">*添加字段名</label>
		    <div class="controls">
			<input type="text" id="approveInputName" class="grd-white" />
		    </div>
		</div>
		<div class="control-group">
		    <label class="control-label" for="inputSelectMulti">哪些频骤可填写</label>
		    <div class="controls">
			<select id="approveSteps" data-form="select2" style="width:500px" data-placeholder="添加步骤" multiple="">
			</select>
		    </div>
		</div>
		<div class="control-group" id="approveInitC">
		    <label class="control-label" for="inputAuto">初始值</label>
		    <div class="controls">
			<input type="text" id="approveInit" class="grd-white" />
		    </div>
		</div>
		<div class="control-group" id="approveOptionsC" style="display:none;">
		    <label class="control-label" for="inputSelectMulti">菜单选项&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="javascript:;" node-act="addlink" style="color:blue;">添加新选项 </a></label>
		    <div class="controls">
			<select id="approveOptions" style="width:500px" data-placeholder="添加选项" multiple="">
				<option selected="selected">同意</option>
				<option selected="selected">不同意</option>
			</select>
		    </div>
		</div>
		<div class="control-group" id="approveNewOptionC" style="display:none;">
		    <div class="controls">
			<input type="text" id="approveNewOption" class="grd-white" /><a href="javascript:;" node-act="addOption" style="color:blue;">添加</a>
		    </div>
		</div>

	    </form>
	</div>
	<div class="modal-footer">
	    <input type="button" form="form-recover" class="btn btn-primary" value="保存" node-act="sure" />
	    <button class="btn" data-dismiss="modal" aria-hidden="true" node-act="cancel">取消</button>
	</div>
</div>
<!-- /审批，报表字段-->

<!-- 备注 -->
<div id="layer_updatetask" class="modal fade hide" tabindex="-1" role="dialog" aria-labelledby="modal-recoverLabel" aria-hidden="true">
	<div class="modal-header">
	    <button type="button" class="close" data-dismiss="modal" aria-hidden="true" node-act="close">&times;</button>
	    <h4 id="modal-recoverLabel">备注</h4>
	</div>
	<div class="modal-body">
	    <form id="form-recover" method="post" />
		<div class="control-group">
		    
		    <div class="controls" style='margin-bottom:10px;'>
			<textarea id="inputEditorSimple" class="" rows="4" data-form="wysihtml5" placeholder="Enter text ..." style="padding:4px 0;width:100%;"></textarea>
		    </div>
		    <div class="controls" style='margin-bottom:10px;'>
			<div class="uploader" id="uniform-inputUpload"><input type="file" data-form="uniform" id="task_file_input" size="19" style="opacity: 0;"><span class="filename">No file selected</span><span class="action">Choose File</span></div>
		    </div>
		    <div class="controls email-fujian" id="task_file_list">
			<dl>
			</dl>
		    </div>
		    <div class="control-group">
			    <label class="control-label" for="inputSelect">任务进度</label>
			    <div class="controls">
				<select id="inputSelect" data-form="select2" style="width:200px" data-placeholder="Your Favorite Type of Bear">
				    <option />未启动
				    <option />已启动
				    <option />25%
				    <option />50%
				    <option selected="" />75%
				    <option disabled="" />已完成
				    <option />暂停
				</select>
			    </div>
			</div>

		</div>
	    </form>
	</div>
	<div class="modal-footer">
	    <input type="button" form="form-recover" class="btn btn-primary" value="保存" node-act="sure" />
	    <button class="btn" data-dismiss="modal" aria-hidden="true" node-act="cancel" >取消</button>
	</div>
</div>
<!-- /备注-->