<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title><?=$title?></title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="" />
        <meta name="author" content="stilearning" />
        <?php foreach ($stylesheets as $stylesheet):?>
            <link href="<?=$stylesheet?>" rel="stylesheet" />
        <?php endforeach;?>
        <?php foreach ($local_stylesheets as $stylesheet):?>
            <link href="<?=$stylesheet?>" rel="stylesheet" />
        <?php endforeach;?>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    </head>
    <body>
        <!-- section header -->
        <header class="header" data-spy="affix" data-offset-top="0">
            <!--nav bar helper-->
            <?=$header?>
            <!--/nav bar helper-->
        </header>

        <!-- section content -->
        <section class="section">
            <div class="row-fluid">
                <!-- span side-left -->
                <div class="span1">
                    <!--side bar-->
                    <?=$menu?>
                    <!--/side bar -->
                </div>
		<!-- span side-left -->
                <!-- span content -->
                <?=$content?>
                <!-- span side-right -->
                <div class="span2">
                    <!-- side-right -->
                    <?=$panel?>
                    <!-- /side-right -->
                </div>
                <!-- /span side-right -->
            </div>
        </section>
        <!-- section footer -->
        <?=$footer?>
    </body>
</html>
