<!-- span content -->
<div class="span9">
    <!-- content -->
    <div class="content">
        <!-- content-header -->
        <div class="content-header">
            <ul class="content-header-action pull-right">
                <li>
                    <a href="#">
                        <span data-chart="peity-bar" data-height="32" data-colours='["#00A600", "#00A600"]'>5,3,9,6,5,9,7,3,5,2</span>
                        <div class="action-text color-green">8765 <span class="helper-font-small color-silver-dark">今日备忘</span></div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="#">
                        <span data-chart="peity-bar" data-height="32" data-colours='["#00A0B1", "#00A0B1"]'>9,7,9,6,3,5,3,5,5,2</span>
                        <div class="action-text color-teal">1437 <span class="helper-font-small color-silver-dark">今日邮件</span></div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="#">
                        <span data-chart="peity-bar" data-height="32" data-colours='["#BF1E4B", "#BF1E4B"]'>6,5,9,7,3,5,2,5,3,9</span>
                        <div class="action-text color-red">4367 <span class="helper-font-small color-silver-dark">今日审批</span></div>
                    </a>
                </li>
            </ul>
            <h2><i class="icofont-home"></i> 主面板 <small>早安，招融文化</small></h2>
        </div><!-- /content-header -->

        <!-- content-breadcrumb -->
        <div class="content-breadcrumb">
            <!--breadcrumb-nav-->
            <ul class="breadcrumb-nav pull-right">
                <li class="divider"></li>
                <li class="btn-group">
                    <a href="#" class="btn btn-small btn-link dropdown-toggle" data-toggle="dropdown">
                        <i class="icofont-tasks"></i> 部门
                        <i class="icofont-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Some Action</a></li>
                        <li><a href="#">Other Action</a></li>
                        <li class="divider"></li>
                        <li><a href="#">Something Else</a></li>
                    </ul>
                </li>
                <li class="divider"></li>
                <li class="btn-group">
                    <a href="#" class="btn btn-small btn-link">
                        <i class="icofont-file"></i> 审批 <span class="color-red">(+12)</span>
                    </a>
                </li>
                <li class="divider"></li>
                <li class="btn-group">
                    <a href="#" class="btn btn-small btn-link">
                        <i class="icofont-user"></i> 在线人数 <span class="color-red">(+34)</span>
                    </a>
                </li>
            </ul><!--/breadcrumb-nav-->

            <!--breadcrumb-->
            <ul class="breadcrumb">
                <li><a href="index.html"><i class="icofont-home"></i> 主面板</a> <span class="divider">&rsaquo;</span></li>
                <li class="active">概况</li>
            </ul><!--/breadcrumb-->
        </div><!-- /content-breadcrumb -->

        <!-- content-body -->
        <div class="content-body">
            <!-- dashboar -->
            <!-- shortcut button -->
            <div class="shortcut-group">
                <ul class="a-btn-group">
                    <li>
                        <a href="#" class="a-btn grd-white" rel="tooltip" title="add new post">
                            <span></span>
                            <span><i class="icofont-edit color-silver-dark"></i></span>
                            <span class="color-silver-dark"><i class="icofont-file color-silver-dark"></i></span>
                        </a>
                    </li>
                    <li>
                        <a href="#" class="a-btn grd-white" rel="tooltip" title="upload something">
                            <span></span>
                            <span><i class="icofont-upload color-silver-dark"></i></span>
                            <span class="color-silver-dark"><i class="icofont-upload-alt color-silver-dark"></i></span>
                        </a>
                    </li>
                    <li>
                        <a href="#" class="a-btn grd-white" rel="tooltip" title="message">
                            <span></span>
                            <span><i class="icofont-envelope color-silver-dark"></i></span>
                            <span class="color-silver-dark"><i class="icofont-envelope-alt color-teal"></i></span>
                            <div class="badge badge-info">9</div> <!--don't use span here!-->
                        </a>
                    </li>
                    <li>
                        <a href="#" class="a-btn grd-white" rel="tooltip" title="invoice">
                            <span></span>
                            <span><i class="icofont-barcode color-silver-dark"></i></span>
                            <span class="color-silver-dark"><i class="icofont-shopping-cart color-red"></i></span>
                            <div class="label label-important">2</div> <!--don't use span here!-->
                        </a>
                    </li>
                    <li>
                        <a href="#" class="a-btn grd-white" rel="tooltip" title="check statistics">
                            <span></span>
                            <span><i class="icofont-bar-chart color-silver-dark"></i></span>
                            <span class="color-silver-dark"><i class="typicn-lineChart"></i></span>
                        </a>
                    </li>
                    <li class="clearfix"></li>
                </ul>
            </div><!-- /shortcut button -->

            <div class="divider-content"><span></span></div>

            <!-- tab stat -->
            <div class="box-tab corner-all">
                <div class="box-header corner-top">
                    <div class="header-control pull-right">
                        <a data-box="collapse"><i class="icofont-caret-up"></i></a>
                    </div>
                    <ul class="nav nav-tabs" id="tab-stat">
                        <li class="active"><a data-toggle="tab" href="#system-stat">项目状态</a></li>
                        <li><a data-toggle="tab" href="#server-stat">系统状态</a></li>
                    </ul>
                </div>
                <div class="box-body">
                    <div class="tab-content">
                        <div class="tab-pane fade in active" id="system-stat">
                            <div class="row-fluid">
                                <div class="span4">
                                    <div class="dashboard-stat">
                                        <div id="visitor-stat" class="chart" style="height: 120px;"></div>
                                        <div class="stat-label grd-green color-white">今日备忘</div>
                                    </div>
                                </div>
                                <div class="span4">
                                    <div class="dashboard-stat">
                                        <div id="order-stat" class="chart" style="height: 120px;"></div>
                                        <div class="stat-label grd-teal color-white">今日邮件</div>
                                    </div>
                                </div>
                                <div class="span4">
                                    <div class="dashboard-stat">
                                        <div id="user-stat" class="chart" style="height: 120px;"></div>
                                        <div class="stat-label grd-red color-white">今日审批</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="tab-pane fade" id="server-stat">
                            <div class="row-fluid">
                                <div class="span4">
                                    <div class="dashboard-stat" rel="tooltip" title="usage 2465kb of 5000kb">
                                        <input data-chart="knob" type="text" data-readonly="true" data-width="120" data-height="120" data-fgcolor="#00A600" value="2465" data-min="0" data-max="5000" />
                                        <div class="stat-label grd-green color-white">文件数</div>
                                    </div>
                                </div>
                                <div class="span4">
                                    <div class="dashboard-stat" rel="tooltip" title="usage 8795kb of 10000kb">
                                        <input data-chart="knob" type="text" data-readonly="true" data-width="120" data-height="120" data-fgcolor="#00A0B1" value="8795" data-min="0" data-max="10000" />
                                        <div class="stat-label grd-teal color-white">存储空间</div>
                                    </div>
                                </div>
                                <div class="span4">
                                    <div class="dashboard-stat" rel="tooltip" title="server condition 70%, it's good!">
                                        <input data-chart="knob" type="text" data-readonly="true" data-width="120" data-height="120" data-fgcolor="#AC193D" value="70" data-min="0" data-max="100" />
                                        <div class="stat-label grd-red color-white">空间状态</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div><!-- /tab stat -->

            <!-- tab resume content -->
            <div class="row-fluid">
                <!-- tab resume update -->
                <div class="span6">
                    <div class="box-tab corner-all">
                        <div class="box-header corner-top">
                            <!--tab action-->
                            <div class="header-control pull-right">
                                <a data-box="collapse"><i class="icofont-caret-up"></i></a>
                                <a data-box="close" data-hide="rotateOutDownLeft">&times;</a>
                            </div>
                            <ul class="nav nav-pills">
                                <!--tab menus-->
                                <li class="active"><a data-toggle="tab" href="#recent-orders">最新公告</a></li>
                                <li><a data-toggle="tab" href="#recent-posts">未读公告</a></li><!--/tab menus-->
                            </ul>
                        </div>
                        <div class="box-body">
                            <!-- widgets-tab-body -->
                            <div class="tab-content">
                                <div class="tab-pane fade in active" id="recent-orders">
                                    <div class="media">
                                        <a class="pull-left" href="#">
                                            <img class="media-object" data-src="js/holder.js/64x64" />
                                        </a>
                                        <div class="media-body">
                                            <h4 class="media-heading"><a href="#">Lorem ipsum </a><small class="helper-font-small">by john doe on 22 aug 2012, ip 192.168.56.7</small></h4>
                                            <p>Raw denim you probably haven't heard of them jean shorts Austin.</p>
                                            <div class="btn-group pull-right">
                                                <a href="#" class="btn btn-mini">打开</a>
                                                <a href="#" class="btn btn-mini btn-danger">删除</a>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="media">
                                        <a class="pull-left" href="#">
                                            <img class="media-object" data-src="js/holder.js/64x64" />
                                        </a>
                                        <div class="media-body">
                                            <h4 class="media-heading"><a href="#">Lorem ipsum </a><small class="helper-font-small">by jane smith on 18 aug 2012, ip 192.168.56.7</small></h4>
                                            <p>Food truck fixie locavore, accusamus mcsweeney's marfa nulla single-origin coffee squid.</p>
                                            <div class="btn-group pull-right">
                                                <a href="#" class="btn btn-mini">打开</a>
                                                <a href="#" class="btn btn-mini btn-danger">删除</a>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="media">
                                        <a class="pull-left" href="#">
                                            <img class="media-object" data-src="js/holder.js/64x64" />
                                        </a>
                                        <div class="media-body">
                                            <h4 class="media-heading"><a href="#">Lorem ipsum </a><small class="helper-font-small">by john smith on 18 aug 2012, ip 192.168.56.7</small></h4>
                                            <p>Etsy mixtape wayfarers, ethical wes anderson tofu before they sold out mcsweeney's organic lomo retro fanny pack lo-fi farm-to-table readymade.</p>
                                            <div class="btn-group pull-right">
                                                <a href="#" class="btn btn-mini">打开</a>
                                                <a href="#" class="btn btn-mini btn-danger">删除</a>
                                            </div>
                                        </div>
                                    </div>
                                    <a href="#" class="btn btn-small btn-link pull-right">查看所有 &rarr;</a>
                                </div>
                                <div class="tab-pane fade" id="recent-posts">
                                    <div class="media">
                                        <a class="pull-left" href="#">
                                            <img class="media-object" data-src="js/holder.js/64x64" />
                                        </a>
                                        <div class="media-body">
                                            <h4 class="media-heading"><a href="#">Tortor dapibus </a><small class="helper-font-small">by jane smith on 11 aug 2012, ip 192.168.56.7</small></h4>
                                            <p>Etsy mixtape wayfarers, ethical wes anderson tofu before they sold out mcsweeney's organic lomo retro fanny pack lo-fi farm-to-table readymade.</p>
                                            <div class="btn-group pull-right">
                                                <a href="#" class="btn btn-mini">打开</a>
                                                <a href="#" class="btn btn-mini btn-danger">删除</a>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="media">
                                        <a class="pull-left" href="#">
                                            <img class="media-object" data-src="js/holder.js/64x64" />
                                        </a>
                                        <div class="media-body">
                                            <h4 class="media-heading"><a href="#">Tortor dapibus </a><small class="helper-font-small">by john doe on 10 aug 2012, ip 192.168.56.7</small></h4>
                                            <p>Vegan fanny pack odio cillum wes anderson 8-bit, sustainable jean shorts beard ut DIY ethical culpa terry richardson biodiesel.</p>
                                            <div class="btn-group pull-right">
                                                <a href="#" class="btn btn-mini">打开</a>
                                                <a href="#" class="btn btn-mini btn-danger">删除</a>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="media">
                                        <a class="pull-left" href="#">
                                            <img class="media-object" data-src="js/holder.js/64x64" />
                                        </a>
                                        <div class="media-body">
                                            <h4 class="media-heading"><a href="#">Tortor dapibus </a><small class="helper-font-small">by jane doe on 9 aug 2012, ip 192.168.56.7</small></h4>
                                            <p>Messenger bag gentrify pitchfork tattooed craft beer, iphone skateboard locavore carles etsy salvia banksy hoodie helvetica. DIY synth PBR banksy irony. Leggings gentrify squid 8-bit cred pitchfork.</p>
                                            <div class="btn-group pull-right">
                                                <a href="#" class="btn btn-mini">打开</a>
                                                <a href="#" class="btn btn-mini btn-danger">删除</a>
                                            </div>
                                        </div>
                                    </div>
                                    <a href="#" class="btn btn-small btn-link pull-right">查看所有 &rarr;</a>
                                </div>
                            </div><!--/widgets-tab-body-->
                        </div><!--/box-body-->
                    </div><!--/box-tab-->
                </div><!-- tab resume update -->
                <div class="span6">
                    <div class="box corner-all">
                        <div class="box-header corner-top grd-white">
                            <div class="header-control">
                                <a data-box="collapse"><i class="icofont-caret-up"></i></a>
                                <a data-box="close" data-hide="rotateOutDownRight">&times;</a>
                            </div>
                            <span><i class="icofont-envelope"></i> 邮件</span>
                        </div>
                        <div class="box-body">
                            <form />
                                <div class="control-group">
                                    <label class="control-label">收件人</label>
                                    <div class="controls">
                                        <input type="hidden" class="input-block-level" name="reseiver" value="johndoe@mail.com, janedoe@mail.com, johnsmith@mail.com, janesmith@mail.com" />
                                    </div>
                                </div>
                                <div class="control-group">
                                    <label class="control-label">主题：</label>
                                    <div class="controls">
                                        <input type="text" class="input-block-level grd-white" name="subject" />
                                    </div>
                                </div>
                                <div class="control-group">
                                    <label class="control-label">内容：</label>
                                    <div class="controls">
                                        <textarea name="message" data-form="wysihtml5" rows="6" class="span11"></textarea>
                                    </div>
                                </div>
                                <div class="form-actions">
                                    <input type="reset" class="btn" value="取消" />
                                    <input type="submit" class="btn btn-primary" value="发送" />
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div><!-- tab stat -->

            <!--schedule-->
            <div class="box corner-all">
                <div class="box-header grd-white color-silver-dark corner-top">
                    <div class="header-control">
                        <a data-box="collapse"><i class="icofont-caret-up"></i></a>
                    </div>
                    <span>备忘录</span>
                </div>
                <div class="box-body">
                    <div id="schedule"></div>
                </div>
            </div>
            <!--schedule-->

            <!--/dashboar-->
        </div><!--/content-body -->
    </div><!-- /content -->
</div>
<!-- /span content -->