<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>StoneOA</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="" />
        <meta name="author" content="stilearning" />

        <!-- google font -->
        <!--link href="http://fonts.googleapis.com/css?family=Aclonica:regular" rel="stylesheet" type="text/css" /-->
        
        <!-- styles -->
        <link href="/public/css/bootstrap.css" rel="stylesheet" />
        <link href="/public/css/bootstrap-responsive.css" rel="stylesheet" />
        <link href="/public/css/stilearn.css" rel="stylesheet" />
        <link href="/public/css/stilearn-responsive.css" rel="stylesheet" />
        <link href="/public/css/stilearn-helper.css" rel="stylesheet" />
        <link href="/public/css/stilearn-icon.css" rel="stylesheet" />
        <link href="/public/css/font-awesome.css" rel="stylesheet" />
        <link href="/public/css/animate.css" rel="stylesheet" />
        <link href="/public/css/uniform.default.css" rel="stylesheet" />
        
        <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
        <!--[if lt IE 9]>
          <!--script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script-->
        <![endif]-->
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" /></head>

    <body>
        <!-- section header -->
        <header class="header" data-spy="affix" data-offset-top="0">
            <!--nav bar helper-->
            <div class="navbar-helper">
                <div class="row-fluid">
                    <!--panel site-name-->
                    <div class="span2">
                        <div class="panel-sitename">
				<h2><img src='/public/img/logo.png'/></h2>
			</div>
                    </div>
                    <!--/panel name-->
                </div>
            </div><!--/nav bar helper-->
        </header>
        
        <!-- section content -->
        <section class="section">
            <div class="shortcut-group signin-form">
          
                    <!--Sign In-->
                    <div class="span5 ">
                        <div class="box corner-all">
                            <div class="box-header grd-teal color-white corner-top">
                                <span>登录:</span>
                            </div>
                            <div class="box-body bg-white">
                                <form id="sign-in" method="post"/>
                                    <div class="control-group">
                                        <label class="control-label">用户名</label>
                                        <div class="controls">
                                            <input type="text" class="input-block-level" data-validate="{required: true, messages:{required:'请输入用户名'}}" name="login_username" id="login_username" autocomplete="off" />
                                        </div>
                                    </div>
                                    <div class="control-group">
                                        <label class="control-label">密码</label>
                                        <div class="controls">
                                            <input type="password" class="input-block-level" data-validate="{required: true, messages:{required:'请输入密码'}}" name="login_password" id="login_password" autocomplete="off" />
                                        </div>
                                    </div>
                                    <div class="control-group">
                                        <label class="checkbox" style="padding-left:0;">
                                            <input type="checkbox" data-form="uniform" name="remember_me" id="autologin" value="yes" /> 自动登录
                                        </label>
                                    </div>
				    <div class="control-group error" id="tips" style="display:none;">
                                        <div class="controls">
                                            
                                        </div>
                                    </div>
                                    <div class="form-actions">
                                        <input type="button" class="btn btn-block btn-large btn-primary" value="登录" id="loginbtn"/>
                                        <p class="recover-account"><a href="javascript:;" id="forget-passwd" class="link">忘记密码？</a></p>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div><!--/Sign In-->
                    

            </div><!-- /shortcut-group -->
            
            <!-- modal recover -->
            <div id="modal-recover" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="modal-recoverLabel" aria-hidden="true">
		<!--step1-->
		<div id="step1">
			<div class="modal-header">
			    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
			    <h3 id="modal-recoverLabel">身份验证<!--small>身份验证</small--></h3>
			</div>
			<div class="modal-body">
			    <form id="form-recover" method="post" />
				<div class="control-group error">
				    <div class="controls">
					<p class="helper-font-small" id="safeemail">安全邮箱：<span></span></p>
					<!--input type="text" /-->
					<p class="help-block helper-font-small" id="findpswTip"></p>
				    </div>
				</div>
			    </form>
			</div>
			<!--div class="modal-body">
				<div class="control-group">
				    <p class="help-block helper-font-small" id="findpswTip"></p>
				</div>
			</div-->
			<div class="modal-footer">
			    <!--input type="button" id="next-to-step2" form="form-recover" class="btn btn-primary" value="下一步" /-->
			    <a href="javascript:;" class="btn" id="getToken" style="margin-top:-10px;">发送验证邮件</a>
			</div>    
                </div>
		<!--step2-->
		<div style="display:none;" id="step2">
			<div class="modal-header">
			    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
			    <h3 id="modal-recoverLabel">重置密码<!--small>身份验证</small--></h3>
			</div>
			<!--重置密码-->
			<div class="modal-body">
			    <form id="form-recover" method="post" />
				<div class="control-group">
				    <div class="controls">
					<p class="help-block helper-font-small">新密码：</p>
					<input type="password" name="psw" />
					<p class="help-block helper-font-small">确认密码：</p>
					<input type="password" name="repsw" />
					<p class="help-block helper-font-small">验证码：</p>
					<input type="text" name="token" />
				    </div>
				</div>
			    </form>
			</div>
			<!--成功-->
			<div class="modal-body">
				<div class="control-group error">
				    <p class="help-block helper-font-small" id="updatepswTip"></p>
				</div>
			</div>

			<div class="modal-footer">
			    <a href="javascript:;" id="changePsw" class="btn btn-primary">完成</a>
			</div>
		</div>

            </div>
            <!-- /modal recover-->
        </section>
        <script src="/public/js/jquery.js"></script>
        <script src="/public/js/bootstrap.js"></script>
        <script src="/public/js/uniform/jquery.uniform.js"></script>
        <script src="/public/js/validate/jquery.metadata.js"></script>
        <script src="/public/js/validate/jquery.validate.js"></script>	
	<script src="/public/js/jsonReq.js"></script>
        <script src="/public/stone/system_sign.js"></script>
        
        <script type="text/javascript">
            $(document).ready(function() {                
                // uniform
                $('[data-form=uniform]').uniform();
                // validate
                //$('#sign-in').validate();
                //$('#form-recover').validate();
            })
        </script>
    </body>
</html>
