<!-- span content -->
                <div class="span9">
                    <!-- content -->
                    <div class="content">
                        
                        
                        <!-- content-breadcrumb -->
                        <div class="content-breadcrumb">
                            <!--breadcrumb-nav
                            <ul class="breadcrumb-nav pull-right">
                                <li class="divider"></li>
                                <li class="btn-group">
                                    <a href="#" class="btn btn-small btn-link dropdown-toggle" data-toggle="dropdown">
                                        <i class="icofont-cogs"></i> Controls
                                        <i class="icofont-caret-down"></i>
                                    </a>
                                    <ul class="dropdown-menu">
                                        <li><a tabindex="-1" href="#" class="getDataSelected">Get Data</a></li>
                                        <li><a tabindex="-1" href="#">Delete All</a></li>
                                        <li class="divider"></li>
                                        <li><a tabindex="-1" href="#">Other Action</a></li>
                                    </ul>
                                </li>
                                <li class="divider"></li>
                                <li class="btn-group">
                                    <a href="#" class="btn btn-small btn-link">
                                        <i class="icofont-money"></i> Orders <span class="color-red">(+12)</span>
                                    </a>
                                </li>
                            </ul>/breadcrumb-nav-->
                            
                            <!--breadcrumb-->
                            <ul class="breadcrumb">
                                <li><a href="../system/dashboard"><i class="icofont-home"></i> 主面板</a> <span class="divider">&rsaquo;</span></li>
				<li class="active">上传文件</li>
                            </ul><!--/breadcrumb-->
                        </div><!-- /content-breadcrumb -->
                        
                        <!-- content-body -->
                        <div class="content-body">
                            <!-- gallery -->
                            <div class="row-fluid">
                                <div class="span12">
                                    <div class="gallery">
                                        <div class="gallery-controls top">
                                            
                                            <div class="gallery-category clearfix">
                                                <div class="pull-right">
                                                    
                                                    <div class="btn-group">
                                                        <div class="DTTT btn-group">
								<a class="btn DTTT_button_text btn-upload" id="btn-file-upload" ><span>上传</span><input type="file" class="input-upload"  multiple="multiple"/></a>
								<a class="btn DTTT_button_text" id="btn-create-folder"><span>新建文件夹</span></a>
							</div>
                                                    </div>
                                                </div>
                                                <div class="portfolio-filter">
                                                    <span>筛选 :</span>
                                                    <span class="label"><a class="filterable" href="#all" rel="all">全部</a></span>
                                                    <span class="label"><a class="filterable" href="#ffolder" rel="design">文件夹</a></span>
                                                    <span class="label"><a class="filterable" href="#ftext" rel="design">文本</a></span>
                                                    <span class="label"><a class="filterable" href="#fimage" rel="portofolio">图片</a></span>
                                                    <span class="label"><a class="filterable" href="#ffile" rel="uncategories">文件</a></span>
                                                    <span class="label"><a class="filterable" href="#fmedia" rel="uncategories">媒体</a></span>
                                                    <span class="label"><a class="filterable" href="#fother" rel="uncategories">其它</a></span>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="gallery-content">
                                            <ul class="thumbnails" id="portfolio-list">
                                            </ul>
                                        </div>
                                        <div class="gallery-controls bottom">
                                            <div class="gallery-category">
                                                <!--div class="pull-right">
                                                    <span>文件 当前类型总数 of 全部文件总数</span>
                                                    <span>|</span>
                                                    <div class="btn-group dropup">
                                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                                            <i class="icon-cog" style="margin-top: -7px;"></i>
                                                        </a>
                                                        <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
                                                            <li><a tabindex="-1" href="#" class="getDataSelected">下载全部</a></li>
                                                            <li><a tabindex="-1" href="#">删除所有</a></li>
                                                        </ul>
                                                    </div>
                                                </div-->
                                                <div class="portfolio-filter">
                                                    <span>筛选 :</span>
                                                    <span class="label"><a class="filterable" href="#all" rel="all">全部</a></span>
                                                    <span class="label"><a class="filterable" href="#ffolder" rel="design">文件夹</a></span>
                                                    <span class="label"><a class="filterable" href="#ftext" rel="design">文本</a></span>
                                                    <span class="label"><a class="filterable" href="#fimage" rel="portofolio">图片</a></span>
                                                    <span class="label"><a class="filterable" href="#ffile" rel="uncategories">文件</a></span>
                                                    <span class="label"><a class="filterable" href="#fmedia" rel="uncategories">媒体</a></span>
                                                    <span class="label"><a class="filterable" href="#fother" rel="uncategories">其它</a></span>
                                                </div>
                                            </div>
                                            <!--ul class="pager helper-font-small">
                                                <li class="previous disabled">
                                                    <a href="#">&larr; 上一页</a>
                                                </li>
                                                <li class="disabled"><a href="#">Prev</a></li>
                                                <li class="disabled"><a href="#">1</a></li>
                                                <li><a href="#">3</a></li>
                                                <li><a href="#">4</a></li>
                                                <li><a href="#">5</a></li>
                                                <li><a href="#">6</a></li>
                                                <li><a href="#">Next</a></li>
                                                <li class="next">
                                                    <a href="#">下一页 &rarr;</a>
                                                </li>
                                            </ul-->
                                        </div>
                                    </div>
                                    <!-- Modal Confirm -->
                                    <div id="modalConfirm" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                                            <h3 id="myModalLabel">Confirm</h3>
                                        </div>
                                        <div class="modal-body">
                                            <p>Are you sure want to delete this images?</p>
                                        </div>
                                        <div class="modal-footer">
                                            <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
                                            <button class="btn btn-danger">Yes</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!--/gallery-->
                        </div><!--/content-body -->
                    </div><!-- /content -->
                </div><!-- /span content -->