<!-- span content -->
                <div class="span9">
                    <!-- content -->
                    <div class="content">
                        
                        
                        <!-- content-breadcrumb -->
                        <div class="content-breadcrumb">
                            <!--breadcrumb-nav-->
                            <ul class="breadcrumb-nav pull-right">
                                <li class="divider"></li>
                                <li class="btn-group">
                                    <a href="#" class="btn btn-small btn-link dropdown-toggle" data-toggle="dropdown">
                                        <i class="icofont-cogs"></i> Controls
                                        <i class="icofont-caret-down"></i>
                                    </a>
                                    <ul class="dropdown-menu">
                                        <li><a tabindex="-1" href="#" class="getDataSelected">Get Data</a></li>
                                        <li><a tabindex="-1" href="#">Delete All</a></li>
                                        <li class="divider"></li>
                                        <li><a tabindex="-1" href="#">Other Action</a></li>
                                    </ul>
                                </li>
                                <li class="divider"></li>
                                <li class="btn-group">
                                    <a href="#" class="btn btn-small btn-link">
                                        <i class="icofont-money"></i> Orders <span class="color-red">(+12)</span>
                                    </a>
                                </li>
                            </ul><!--/breadcrumb-nav-->
                            
                            <!--breadcrumb-->
                            <ul class="breadcrumb">
                                <li><a href="index.html"><i class="icofont-home"></i> 主面板</a> <span class="divider">&rsaquo;</span></li>
                                <li class="active">文件</li>
                            </ul><!--/breadcrumb-->
                        </div><!-- /content-breadcrumb -->
                        
                        <!-- content-body -->
                        <div class="content-body">
                            <!-- gallery -->
                            <div class="row-fluid">
                                <div class="span12">
                                    <div class="gallery">
                                        <div id="editor" style="height:300px;"></div>
                                    </div>
                                    <!-- Modal Confirm -->
                                    <div id="modalConfirm" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                                            <h3 id="myModalLabel">Confirm</h3>
                                        </div>
                                        <div class="modal-body">
                                            <p>Are you sure want to delete this images?</p>
                                        </div>
                                        <div class="modal-footer">
                                            <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
                                            <button class="btn btn-danger">Yes</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!--/gallery-->
                        </div><!--/content-body -->
                    </div><!-- /content -->
                </div><!-- /span content -->