<!-- span content -->
<div class="span9">
    <!-- content -->
    <div class="content">
        <!-- content-breadcrumb -->
        <div class="content-breadcrumb">
            <!--breadcrumb-nav-
            <ul class="breadcrumb-nav pull-right">
                <li class="divider"></li>
                <li class="btn-group">
                    <a href="#" class="btn btn-small btn-link dropdown-toggle" data-toggle="dropdown">
                        <i class="icofont-cogs"></i> Controls
                        <i class="icofont-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="#element" class="scroll">Element</a></li>
                        <li><a href="#validation" class="scroll">Validation</a></li>
                        <li><a href="#wizard" class="scroll">Wizard</a></li>
                        <li class="divider"></li>
                        <li><a href="#extending" class="scroll">Extending</a></li>
                        <li><a href="#controls" class="scroll">Controls</a></li>
                        <li class="divider"></li>
                        <li><a href="#buttons" class="scroll">Buttons</a></li>
                    </ul>
                </li>
                <li class="divider"></li>
                <li class="btn-group">
                    <a href="#" class="btn btn-small btn-link">
                        <i class="icofont-user"></i> Users <span class="color-red">(+34)</span>
                    </a>
                </li>
            </ul>/breadcrumb-nav-->

            <!--breadcrumb-->
            <ul class="breadcrumb">
                <li><a href="../system/dashboard"><i class="icofont-home"></i> 首页</a> <span class="divider">&rsaquo;</span></li>
		<li><a href="manages">管理其它邮箱</a> <span class="divider">&rsaquo;</span></li>
                <li class="active">添加其他邮箱帐户</li>
            </ul><!--/breadcrumb-->
        </div><!-- /content-breadcrumb -->

        <!-- content-body -->
        <div class="content-body">
            <!-- form -->
            <div class="row-fluid">
                <div class="span12">

                    <!-- =========================================
                                        ELEMENT
                    =========================================== -->
                    <!--element-->
                    <div id="element" class="row-fluid">
                        <!--span-->
                        <div class="span12">
                            <!--box-->
                            <div class="box corner-all">
                                <!--box header-->
                                <div class="box-header grd-white color-silver-dark corner-top">
                                    <!--div class="header-control">
                                        <a data-box="collapse"><i class="icofont-caret-up"></i></a>
                                        <a data-box="close">&times;</a>
                                    </div-->
                                    <span>添加其他邮箱帐户</span>
                                </div><!--/box header-->
                                <!--box body-->
                                <div class="box-body">
                                    <!--element-->
                                    <form id="mail" class="form-horizontal" />
                                       <div class="control-group">
                                            <label class="control-label" for="inputAuto">邮箱名称：</label>
                                            <div class="controls">
                                                <input type="text" name="name" class="grd-white" />
                                            </div>
                                        </div>
                                        <div class="control-group">
                                            <label class="control-label" for="inputAuto">邮箱帐户：</label>
                                            <div class="controls">
                                                <input type="text" name="username" class="grd-white" />
                                            </div>
                                        </div>
					<div class="control-group">
                                            <label class="control-label" for="inputAuto">邮箱密码：</label>
                                            <div class="controls">
                                                <input type="password" name="password" class="grd-white" />
                                            </div>
                                        </div>
                                        <div class="control-group">
                                            <label class="control-label" for="inputAuto">接收邮件服务器(POP)：</label>
                                            <div class="controls">
                                                <select name="server"  class="grd-white">
                                                    <option value="imap.163.com">163免费邮</option>
                                                    <option value="imap.126.com">126免费邮</option>
                                                    <option value="imap.qq.com">QQ邮箱</option>
                                                    <option value="imap.sina.com">新浪邮箱</option>
                                                    <option value="imap.sohu.com">搜狐邮箱</option>
                                                    <option value="imap.gmail.com">Gmail邮箱</option>
                                                </select>
                                            </div>
                                        </div>
                                        <div class="control-group">
                                            <label class="control-label" for="inputAuto">端口：</label>
                                            <div class="controls">
                                                <input type="text" name="port" value="143" class="grd-white" />
                                                <p><label><input type="checkbox" name="ssl" value="开启SSL" class="grd-white" />开启SSL</label></p>
                                            </div>
                                        </div>
                                        <div class="form-actions">
                                            <button type="button" class="btn btn-primary" id="btn-create">保存</button>
                                            <button type="button" class="btn">取消</button>
                                        </div>
                                    </form>
                                    <!--/element-->
                                </div><!--/box body-->
                            </div><!--/box-->
                        </div><!--/span--> 
                    </div><!--/element-->  
                </div><!--/span-->
            </div><!--/row-fluid-->
            <!--/form-->
        </div><!--/content-body -->
    </div><!-- /content -->
</div>
<!-- /span content -->