<!-- span content -->
<div class="span9">
    <!-- content -->
    <div class="content">
        <!-- content-header 
        <div class="content-header">
            <ul class="content-header-action pull-right">
                <li>
                    <a href="#">
                        <div class="badge-circle grd-green color-white"><i class="icofont-plus-sign"></i></div>
                        <div class="action-text color-green">8765 <span class="helper-font-small color-silver-dark">Visits</span></div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="#">
                        <div class="badge-circle grd-teal color-white"><i class="icofont-user-md"></i></div>
                        <div class="action-text color-teal">1437 <span class="helper-font-small color-silver-dark">Users</span></div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="#">
                        <div class="badge-circle grd-orange color-white">$</div>
                        <div class="action-text color-orange">4367 <span class="helper-font-small color-silver-dark">Orders</span></div>
                    </a>
                </li>
            </ul>
            <h2><i class="icofont-file"></i> Form Elements</h2>
        </div> /content-header -->

        <!-- content-breadcrumb -->
        <div class="content-breadcrumb">
            <!--breadcrumb-nav
            <ul class="breadcrumb-nav pull-right">
                <li class="divider"></li>
                <li class="btn-group">
                    <a href="#" class="btn btn-small btn-link dropdown-toggle" data-toggle="dropdown">
                        <i class="icofont-cogs"></i> Controls
                        <i class="icofont-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="#element" class="scroll">Element</a></li>
                        <li><a href="#validation" class="scroll">Validation</a></li>
                        <li><a href="#wizard" class="scroll">Wizard</a></li>
                        <li class="divider"></li>
                        <li><a href="#extending" class="scroll">Extending</a></li>
                        <li><a href="#controls" class="scroll">Controls</a></li>
                        <li class="divider"></li>
                        <li><a href="#buttons" class="scroll">Buttons</a></li>
                    </ul>
                </li>
                <li class="divider"></li>
                <li class="btn-group">
                    <a href="#" class="btn btn-small btn-link">
                        <i class="icofont-user"></i> Users <span class="color-red">(+34)</span>
                    </a>
                </li>
            </ul>/breadcrumb-nav-->

            <!--breadcrumb-->
            <ul class="breadcrumb">
                <li><a href="../system/dashboard"><i class="icofont-home"></i>主面板</a> <span class="divider">&rsaquo;</span></li>
                <li><a href="set">设置审批</a> <span class="divider">&rsaquo;</span></li>
                <li class="active">新建模版</li>
            </ul><!--/breadcrumb-->
        </div><!-- /content-breadcrumb -->

        <!-- content-body -->
        <div class="content-body">
            <!-- form -->
            <div class="row-fluid">
                <div class="span12">

                    <!-- =========================================
                                        ELEMENT
                    =========================================== -->
                    <!--element-->
                    <div id="element" class="row-fluid">
                        <!--span-->
                        <div class="span12">
                            <!--box-->
                            <div class="box corner-all">
                                <!--box header-->
                                <div class="box-header grd-white color-silver-dark corner-top">
                                    <!--div class="header-control">
                                        <a data-box="collapse"><i class="icofont-caret-up"></i></a>
                                        <a data-box="close">&times;</a>
                                    </div-->
                                    <span>新建模版</span>
                                </div><!--/box header-->
                                <!--box body-->
                                <div class="box-body">
                                    <!--element-->
                                    <form class="form-horizontal" />
					<div class="control-group">
                                            <label class="control-label" for="inputSelect">分类</label>
                                            <div class="controls">
                                                <select id="inputSelect" data-form="select2" style="width:220px" data-placeholder="分类">
                                                    <option />行政
                                                    <option />销售
                                                </select>
                                            </div>
                                        </div>

					<div class="control-group">
                                            <label class="control-label" for="inputAuto">审批名称</label>
                                            <div class="controls">
                                                <input type="text" class="grd-white" />
                                            </div>
                                        </div>
					<div id="approve-steps">
						<div class="control-group">
						    <label class="control-label" for="inputSelectMulti">第1步</label>
						    <div class="controls">
							<p><input type="text" class="grd-white" placeholder='步骤名' />&nbsp;<input type="text" class="grd-white" placeholder='步骤说明' /></p>
							<select id="inputSelectMulti" data-form="select2" style="width:500px" data-placeholder="收件人" multiple="">
							    <option />袁旭
							    <option />高天仪
							    <option selected="" />申晨
							    <option />老林
							</select>
						    </div>
						    
						</div>

						<div class="control-group">
						    <label class="control-label" for="inputSelectMulti">第2步</label>
						    <div class="controls">
							<p><input type="text" class="grd-white" placeholder='步骤名' />&nbsp;<input type="text" class="grd-white" placeholder='步骤说明' /></p>
							<select id="inputSelectMulti" data-form="select2" style="width:500px" data-placeholder="收件人" multiple="">
							    <option />袁旭
							    <option />高天仪
							    <option selected="" />申晨
							    <option />老林
							</select>
						    </div>
						</div>   
					</div>
 
					<div class="control-group">						
					    <div class="controls">
						<button type="button" class="btn btn-primary" id="btn-add-step">添加步骤</button>
					    </div>
					</div> 

					<div class="gallery">
						<div id="editor" style="height:300px;"></div>
					</div>
					<!-- Modal Confirm -->
					<div id="modalConfirm" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
						<div class="modal-header">
						    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
						    <h3 id="myModalLabel">Confirm</h3>
						</div>
						<div class="modal-body">
						    <p>Are you sure want to delete this images?</p>
						</div>
						<div class="modal-footer">
						    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
						    <button class="btn btn-danger">Yes</button>
						</div>
					</div>
					<!-- /Modal Confirm -->
                                        <div class="form-actions">
				            <button type="submit" class="btn btn-primary">保存</button>
					    <button type="submit" class="btn btn-primary">发布</button>
					    <button type="submit" class="btn btn-primary">预览</button>
					    <button type="submit" class="btn btn-primary">删除</button>
                                        </div>
                                    </form>
                                    <!--/element-->
                                </div><!--/box body-->
                            </div><!--/box-->
                        </div><!--/span--> 
                    </div><!--/element-->

                </div><!--/span-->
            </div><!--/row-fluid-->
            <!--/form-->
        </div><!--/content-body -->
    </div><!-- /content -->
</div>
<!-- /span content -->
