<!-- span content -->
<div class="span9">
    <!-- content -->
    <div class="content">
        <!-- content-header 
        <div class="content-header">
            <ul class="content-header-action pull-right">
                <li>
                    <a href="#">
                        <div class="badge-circle grd-green color-white"><i class="icofont-plus-sign"></i></div>
                        <div class="action-text color-green">8765 <span class="helper-font-small color-silver-dark">Visits</span></div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="#">
                        <div class="badge-circle grd-teal color-white"><i class="icofont-user-md"></i></div>
                        <div class="action-text color-teal">1437 <span class="helper-font-small color-silver-dark">Users</span></div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="#">
                        <div class="badge-circle grd-orange color-white">$</div>
                        <div class="action-text color-orange">4367 <span class="helper-font-small color-silver-dark">Orders</span></div>
                    </a>
                </li>
            </ul>
            <h2><i class="icofont-file"></i> Form Elements</h2>
        </div> /content-header -->

        <!-- content-breadcrumb -->
        <div class="content-breadcrumb">
            <!--breadcrumb-nav
            <ul class="breadcrumb-nav pull-right">
                <li class="divider"></li>
                <li class="btn-group">
                    <a href="#" class="btn btn-small btn-link dropdown-toggle" data-toggle="dropdown">
                        <i class="icofont-cogs"></i> Controls
                        <i class="icofont-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="#element" class="scroll">Element</a></li>
                        <li><a href="#validation" class="scroll">Validation</a></li>
                        <li><a href="#wizard" class="scroll">Wizard</a></li>
                        <li class="divider"></li>
                        <li><a href="#extending" class="scroll">Extending</a></li>
                        <li><a href="#controls" class="scroll">Controls</a></li>
                        <li class="divider"></li>
                        <li><a href="#buttons" class="scroll">Buttons</a></li>
                    </ul>
                </li>
                <li class="divider"></li>
                <li class="btn-group">
                    <a href="#" class="btn btn-small btn-link">
                        <i class="icofont-user"></i> Users <span class="color-red">(+34)</span>
                    </a>
                </li>
            </ul>/breadcrumb-nav-->

            <!--breadcrumb-->
            <ul class="breadcrumb">
                <li><a href="../system/dashboard"><i class="icofont-home"></i>主面板</a> <span class="divider">&rsaquo;</span></li>
                <li><a href="set">设置审批</a> <span class="divider">&rsaquo;</span></li>
                <li class="active">新建模版</li>
            </ul><!--/breadcrumb-->
        </div><!-- /content-breadcrumb -->

        <!-- content-body -->
        <div class="content-body">
            <!-- form -->
            <div class="row-fluid">
                <div class="span12">

                    <!-- =========================================
                                        ELEMENT
                    =========================================== -->
                    <!--element-->
                    <div id="element" class="row-fluid">
                        <!--span-->
                        <div class="span12">
                            <!--box-->
                            <div class="box corner-all">
                                <!--box header-->
                                <div class="box-header grd-white color-silver-dark corner-top">
                                    <!--div class="header-control">
                                        <a data-box="collapse"><i class="icofont-caret-up"></i></a>
                                        <a data-box="close">&times;</a>
                                    </div-->
                                    <span>新建模版</span>
                                </div><!--/box header-->
                                <!--box body-->
                                <div class="box-body">
                                    <!--element-->
                                    <form class="form-horizontal" action="/approve/templateadd">
					<div class="control-group">
                                            <label class="control-label" for="inputSelect">分类</label>
                                            <div class="controls">
                                                <select id="group_selector" name="type" data-form="select2" style="width:220px" data-placeholder="分类">
                                                </select>
                                            </div>
                                        </div>

					<div class="control-group">
                                            <label class="control-label" for="inputAuto">审批名称</label>
                                            <div class="controls" id="approve_name_container">
                                                
                                            </div>
                                        </div>
					<script id="approve_name_tmpl" type="text/html"><input type="text" class="grd-white" name="name" value="{{name}}" /></script>
					<div id="approve-steps">
						  
					</div>

					<script type="text/html" id="approve-steps-tmpl">
					    {{each list}}
						<div class="control-group" data-id="{{$value.flow_id}}">
						    <label class="control-label" for="inputSelectMulti">第{{$index+1}}步</label>
						    <div class="controls">
							<p><input type="text" name="step" class="grd-white" placeholder='步骤名' value="{{$value.name}}"/>&nbsp;<input type="text" class="grd-white" name="stepdesc" placeholder='步骤说明'  value="{{$value.desc}}"/>{{if $index>1}}<a style="margin:0 0 0 5px;" style="display:none;" href="javascript:;" class="icofont-remove"></a>{{/if}}</p>
						    {{if $index == 0}}
						    <input type="checkbox" name="stependable" value="1" style="display:none;"/>
						    <select name="approver" style="display:none;" data-placeholder="审批人" multiple=""></select>
						    {{else}}
							<select id="contact_{{$index}}" name="approver" data-form="select2" data-placeholder="审批人" style="width:220px;" multiple="">

							</select>
							<label class="checkbox" style='padding:0;'>
							    <input type="checkbox" data-form="uniform" name="stependable" value="1" {{if $value.terminal}}checked{{/if}}/>可在此结束流程
							</label>
						    {{/if}}						    
						    </div>
						</div>
					   {{/each}}
					</script>
 
					<div class="control-group">						
					    <div class="controls">
						<button type="button" class="btn btn-primary" id="btn-add-step">添加步骤</button>
					    </div>
					</div> 

					<div class="gallery">
						<div id="editor" style="height:300px;" name="formcode"></div>
					</div>
					<!-- Modal Confirm -->
					<div id="modalConfirm" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
						<div class="modal-header">
						    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
						    <h3 id="myModalLabel">Confirm</h3>
						</div>
						<div class="modal-body">
						    <p>Are you sure want to delete this images?</p>
						</div>
						<div class="modal-footer">
						    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
						    <button class="btn btn-danger">Yes</button>
						</div>
					</div>
					<!-- /Modal Confirm -->

                                        <div class="form-actions">
				            <button type="button" id="btn-save" class="btn btn-primary">保存</button>
					    <button type="button" id="btn-publish" class="btn btn-primary">发布</button>
					    <button type="button" class="btn btn-primary">预览</button>
					    <button type="button" class="btn btn-primary">删除</button>
                                        </div>
                                    </form>
                                    <!--/element-->
                                </div><!--/box body-->
                            </div><!--/box-->
                        </div><!--/span--> 
                    </div><!--/element-->

                </div><!--/span-->
            </div><!--/row-fluid-->
            <!--/form-->
        </div><!--/content-body -->
    </div><!-- /content -->
</div>
<!-- /span content -->
