<!-- span content -->
 <div class="span9">
     <!-- content -->
     <div class="content">
         <!-- content-header 
         <div class="content-header">
             <ul class="content-header-action pull-right">
                 <li>
                     <a href="#">
                         <div class="badge-circle grd-green color-white"><i class="icofont-plus-sign"></i></div>
                         <div class="action-text color-green">8765 <span class="helper-font-small color-silver-dark">Visits</span></div>
                     </a>
                 </li>
                 <li class="divider"></li>
                 <li>
                     <a href="#">
                         <div class="badge-circle grd-teal color-white"><i class="icofont-user-md"></i></div>
                         <div class="action-text color-teal">1437 <span class="helper-font-small color-silver-dark">Users</span></div>
                     </a>
                 </li>
                 <li class="divider"></li>
                 <li>
                     <a href="#">
                         <div class="badge-circle grd-orange color-white">$</div>
                         <div class="action-text color-orange">4367 <span class="helper-font-small color-silver-dark">Orders</span></div>
                     </a>
                 </li>
             </ul>
             <h2><i class="icofont-table"></i> Tables</h2>
         </div> /content-header -->

         <!-- content-breadcrumb -->
         <div class="content-breadcrumb">
             <!--breadcrumb-nav
             <ul class="breadcrumb-nav pull-right">
                 <li class="divider"></li>
                 <li class="btn-group">
                     <a href="#" class="btn btn-small btn-link">
                         <i class="icofont-money"></i> Orders <span class="color-red">(+12)</span>
                     </a>
                 </li>
                 <li class="divider"></li>
                 <li class="btn-group">
                     <a href="#" class="btn btn-small btn-link">
                         <i class="icofont-user"></i> Users <span class="color-red">(+34)</span>
                     </a>
                 </li>
                 <li class="divider"></li>
                 <li class="btn-group">
                     <a href="#" class="btn btn-small btn-link dropdown-toggle" data-toggle="dropdown">
                         <i class="icofont-tasks"></i> Tasks
                         <i class="icofont-caret-down"></i>
                     </a>
                     <ul class="dropdown-menu">
                         <li><a href="#">Some Action</a></li>
                         <li><a href="#">Other Action</a></li>
                         <li class="divider"></li>
                         <li><a href="#">Something Else</a></li>
                     </ul>
                 </li>
             </ul>/breadcrumb-nav-->

             <!--breadcrumb-->
             <ul class="breadcrumb">
                 <li><a href="../system/dashboard"><i class="icofont-home"></i> 主面板</a> <span class="divider">&rsaquo;</span></li>
                 <li class="active">审批</li>
             </ul><!--/breadcrumb-->
         </div><!-- /content-breadcrumb -->

         <!-- content-body -->
         <div class="content-body">
             <!-- tables -->
             <!--datatables tools-->
             <div class="row-fluid">
                 <div class="span12">
                     <div class="box corner-all">
                         <div class="box-header grd-white corner-top">
                             <!--div class="header-control">
                                 <a data-box="collapse"><i class="icofont-caret-up"></i></a>
                                 <a data-box="close" data-hide="bounceOutRight">&times;</a>
                             </div-->
                             <span>审批列表</span>
                         </div>
                         <div class="box-body">
                             <table id="datatables" class="table table-bordered table-striped responsive mail">
                                 <thead>
                                     <tr>
                                         <th><input type="checkbox" data-form="uniform" name="inputCheckbox"></th>
                                         <th>发布人</th>
                                         <th>题目</th>
                                         <th>时间</th>
                                         <th>附件</th>
                                     </tr>
                                 </thead>
                                 <tbody>
                                     <tr class="odd gradeX">
                                         <td><input type="checkbox" data-form="uniform" name="inputCheckbox"></td>
                                         <td>Internet
                                             Explorer 4.0<span>[草稿]</span></td>
                                         <td>Win 95+</td>
                                         <td class="center"> 4</td>
                                         <td class="center">X</td>
                                     </tr>
                                     <tr class="even gradeC">
                                         <td><input type="checkbox" data-form="uniform" name="inputCheckbox"></td>
                                         <td>Internet
                                             Explorer 5.0<i class="icon-star"></i></td>
                                         <td>Win 95+</td>
                                         <td class="center">5</td>
                                         <td class="center">C</td>
                                     </tr>
                                     <tr class="odd gradeA">
                                         <td><input type="checkbox" data-form="uniform" name="inputCheckbox"></td>
                                         <td>Internet
                                             Explorer 5.5</td>
                                         <td>Win 95+<em>2b袁旭</em></td>
                                         <td class="center">5.5</td>
                                         <td class="center">A</td>
                                     </tr>
                                     <tr class="even gradeA">
                                         <td><input type="checkbox" data-form="uniform" name="inputCheckbox"></td>
                                         <td>Internet
                                             Explorer 6</td>
                                         <td>Win 98+</td>
                                         <td class="center">6</td>
                                         <td class="center">A</td>
                                     </tr>
                                     <tr class="odd gradeA">
                                         <td><input type="checkbox" data-form="uniform" name="inputCheckbox"></td>
                                         <td>Internet Explorer 7</td>
                                         <td>Win XP SP2+</td>
                                         <td class="center">7</td>
                                         <td class="center">A</td>
                                     </tr>
                                     <tr class="even gradeA">
                                         <td><input type="checkbox" data-form="uniform" name="inputCheckbox"></td>
                                         <td>AOL browser (AOL desktop)</td>
                                         <td>Win XP</td>
                                         <td class="center">6</td>
                                         <td class="center">A</td>
                                     </tr>
                                     <tr class="gradeA">
                                         <td><input type="checkbox" data-form="uniform" name="inputCheckbox"></td>
                                         <td>Firefox 1.0</td>
                                         <td>Win 98+ / OSX.2+</td>
                                         <td class="center">1.7</td>
                                         <td class="center">A</td>
                                     </tr>
                                     <tr class="gradeA">
                                         <td><input type="checkbox" data-form="uniform" name="inputCheckbox"></td>
                                         <td>Firefox 1.5</td>
                                         <td>Win 98+ / OSX.2+</td>
                                         <td class="center">1.8</td>
                                         <td class="center">A</td>
                                     </tr>
                                     <tr class="gradeA">
                                         <td><input type="checkbox" data-form="uniform" name="inputCheckbox"></td>
                                         <td>Firefox 2.0</td>
                                         <td>Win 98+ / OSX.2+</td>
                                         <td class="center">1.8</td>
                                         <td class="center">A</td>
                                     </tr>
                                     <tr class="gradeA">
                                         <td><input type="checkbox" data-form="uniform" name="inputCheckbox"></td>
                                         <td>Firefox 3.0</td>
                                         <td>Win 2k+ / OSX.3+</td>
                                         <td class="center">1.9</td>
                                         <td class="center">A</td>
                                     </tr>
                                     <tr class="gradeA">
                                         <td><input type="checkbox" data-form="uniform" name="inputCheckbox"></td>
                                         <td>Camino 1.0</td>
                                         <td>OSX.2+</td>
                                         <td class="center">1.8</td>
                                         <td class="center">A</td>
                                     </tr>
                                     <tr class="gradeA">
                                         <td><input type="checkbox" data-form="uniform" name="inputCheckbox"></td>
                                         <td>Camino 1.5</td>
                                         <td>OSX.3+</td>
                                         <td class="center">1.8</td>
                                         <td class="center">A</td>
                                     </tr>
                                     <tr class="gradeA">
                                         <td><input type="checkbox" data-form="uniform" name="inputCheckbox"></td>
                                         <td>Netscape 7.2</td>
                                         <td>Win 95+ / Mac OS 8.6-9.2</td>
                                         <td class="center">1.7</td>
                                         <td class="center">A</td>
                                     </tr>
                                     <tr class="gradeA">
                                         <td><input type="checkbox" data-form="uniform" name="inputCheckbox"></td>
                                         <td>Netscape Browser 8</td>
                                         <td>Win 98SE+</td>
                                         <td class="center">1.7</td>
                                         <td class="center">A</td>
                                     </tr>
                                     <tr class="gradeA">
                                         <td><input type="checkbox" data-form="uniform" name="inputCheckbox"></td>
                                         <td>Netscape Navigator 9</td>
                                         <td>Win 98+ / OSX.2+</td>
                                         <td class="center">1.8</td>
                                         <td class="center">A</td>
                                     </tr>
                                     <tr class="gradeA">
                                         <td><input type="checkbox" data-form="uniform" name="inputCheckbox"></td>
                                         <td>Mozilla 1.0</td>
                                         <td>Win 95+ / OSX.1+</td>
                                         <td class="center">1</td>
                                         <td class="center">A</td>
                                     </tr>
                                     <tr class="gradeA">
                                         <td><input type="checkbox" data-form="uniform" name="inputCheckbox"></td>
                                         <td>Mozilla 1.1</td>
                                         <td>Win 95+ / OSX.1+</td>
                                         <td class="center">1.1</td>
                                         <td class="center">A</td>
                                     </tr>
                                     <tr class="gradeA">
                                         <td><input type="checkbox" data-form="uniform" name="inputCheckbox"></td>
                                         <td>Mozilla 1.2</td>
                                         <td>Win 95+ / OSX.1+</td>
                                         <td class="center">1.2</td>
                                         <td class="center">A</td>
                                     </tr>
                                     <tr class="gradeA">
                                         <td><input type="checkbox" data-form="uniform" name="inputCheckbox"></td>
                                         <td>Mozilla 1.3</td>
                                         <td>Win 95+ / OSX.1+</td>
                                         <td class="center">1.3</td>
                                         <td class="center">A</td>
                                     </tr>
                                     <tr class="gradeA">
                                         <td><input type="checkbox" data-form="uniform" name="inputCheckbox"></td>
                                         <td>Mozilla 1.4</td>
                                         <td>Win 95+ / OSX.1+</td>
                                         <td class="center">1.4</td>
                                         <td class="center">A</td>
                                     </tr>
                                     <tr class="gradeA">
                                         <td><input type="checkbox" data-form="uniform" name="inputCheckbox"></td>
                                         <td>Mozilla 1.5</td>
                                         <td>Win 95+ / OSX.1+</td>
                                         <td class="center">1.5</td>
                                         <td class="center">A</td>
                                     </tr>
                                     <tr class="gradeA">
                                         <td><input type="checkbox" data-form="uniform" name="inputCheckbox"></td>
                                         <td>Mozilla 1.6</td>
                                         <td>Win 95+ / OSX.1+</td>
                                         <td class="center">1.6</td>
                                         <td class="center">A</td>
                                     </tr>
                                     <tr class="gradeA">
                                         <td><input type="checkbox" data-form="uniform" name="inputCheckbox"></td>
                                         <td>Mozilla 1.7</td>
                                         <td>Win 98+ / OSX.1+</td>
                                         <td class="center">1.7</td>
                                         <td class="center">A</td>
                                     </tr>
                                     <tr class="gradeA">
                                         <td><input type="checkbox" data-form="uniform" name="inputCheckbox"></td>
                                         <td>Mozilla 1.8</td>
                                         <td>Win 98+ / OSX.1+</td>
                                         <td class="center">1.8</td>
                                         <td class="center">A</td>
                                     </tr>
                                     <tr class="gradeA">
                                         <td><input type="checkbox" data-form="uniform" name="inputCheckbox"></td>
                                         <td>Seamonkey 1.1</td>
                                         <td>Win 98+ / OSX.2+</td>
                                         <td class="center">1.8</td>
                                         <td class="center">A</td>
                                     </tr>
                                     <tr class="gradeA">
                                         <td><input type="checkbox" data-form="uniform" name="inputCheckbox"></td>
                                         <td>Epiphany 2.20</td>
                                         <td>Gnome</td>
                                         <td class="center">1.8</td>
                                         <td class="center">A</td>
                                     </tr>
                                     <tr class="gradeA">
                                         <td><input type="checkbox" data-form="uniform" name="inputCheckbox"></td>
                                         <td>Safari 1.2</td>
                                         <td>OSX.3</td>
                                         <td class="center">125.5</td>
                                         <td class="center">A</td>
                                     </tr>
                                     <tr class="gradeA">
                                         <td><input type="checkbox" data-form="uniform" name="inputCheckbox"></td>
                                         <td>Safari 1.3</td>
                                         <td>OSX.3</td>
                                         <td class="center">312.8</td>
                                         <td class="center">A</td>
                                     </tr>
                                     <tr class="gradeA">
                                         <td><input type="checkbox" data-form="uniform" name="inputCheckbox"></td>
                                         <td>Safari 2.0</td>
                                         <td>OSX.4+</td>
                                         <td class="center">419.3</td>
                                         <td class="center">A</td>
                                     </tr>
                                     <tr class="gradeA">
                                         <td><input type="checkbox" data-form="uniform" name="inputCheckbox"></td>
                                         <td>Safari 3.0</td>
                                         <td>OSX.4+</td>
                                         <td class="center">522.1</td>
                                         <td class="center">A</td>
                                     </tr>
                                     <tr class="gradeA">
                                         <td><input type="checkbox" data-form="uniform" name="inputCheckbox"></td>
                                         <td>OmniWeb 5.5</td>
                                         <td>OSX.4+</td>
                                         <td class="center">420</td>
                                         <td class="center">A</td>
                                     </tr>
                                     <tr class="gradeA">
                                         <td><input type="checkbox" data-form="uniform" name="inputCheckbox"></td>
                                         <td>iPod Touch / iPhone</td>
                                         <td>iPod</td>
                                         <td class="center">420.1</td>
                                         <td class="center">A</td>
                                     </tr>
                                     <tr class="gradeA">
                                         <td><input type="checkbox" data-form="uniform" name="inputCheckbox"></td>
                                         <td>S60</td>
                                         <td>S60</td>
                                         <td class="center">413</td>
                                         <td class="center">A</td>
                                     </tr>
                                     <tr class="gradeA">
                                         <td><input type="checkbox" data-form="uniform" name="inputCheckbox"></td>
                                         <td>Opera 7.0</td>
                                         <td>Win 95+ / OSX.1+</td>
                                         <td class="center">-</td>
                                         <td class="center">A</td>
                                     </tr>
                                     <tr class="gradeA">
                                         <td><input type="checkbox" data-form="uniform" name="inputCheckbox"></td>
                                         <td>Opera 7.5</td>
                                         <td>Win 95+ / OSX.2+</td>
                                         <td class="center">-</td>
                                         <td class="center">A</td>
                                     </tr>
                                     <tr class="gradeA">
                                         <td><input type="checkbox" data-form="uniform" name="inputCheckbox"></td>
                                         <td>Opera 8.0</td>
                                         <td>Win 95+ / OSX.2+</td>
                                         <td class="center">-</td>
                                         <td class="center">A</td>
                                     </tr>
                                     <tr class="gradeA">
                                         <td><input type="checkbox" data-form="uniform" name="inputCheckbox"></td>
                                         <td>Opera 8.5</td>
                                         <td>Win 95+ / OSX.2+</td>
                                         <td class="center">-</td>
                                         <td class="center">A</td>
                                     </tr>
                                     <tr class="gradeA">
                                         <td><input type="checkbox" data-form="uniform" name="inputCheckbox"></td>
                                         <td>Opera 9.0</td>
                                         <td>Win 95+ / OSX.3+</td>
                                         <td class="center">-</td>
                                         <td class="center">A</td>
                                     </tr>
                                     <tr class="gradeA">
                                         <td><input type="checkbox" data-form="uniform" name="inputCheckbox"></td>
                                         <td>Opera 9.2</td>
                                         <td>Win 88+ / OSX.3+</td>
                                         <td class="center">-</td>
                                         <td class="center">A</td>
                                     </tr>
                                     <tr class="gradeA">
                                         <td><input type="checkbox" data-form="uniform" name="inputCheckbox"></td>
                                         <td>Opera 9.5</td>
                                         <td>Win 88+ / OSX.3+</td>
                                         <td class="center">-</td>
                                         <td class="center">A</td>
                                     </tr>
                                     <tr class="gradeA">
                                         <td><input type="checkbox" data-form="uniform" name="inputCheckbox"></td>
                                         <td>Opera for Wii</td>
                                         <td>Wii</td>
                                         <td class="center">-</td>
                                         <td class="center">A</td>
                                     </tr>
                                     <tr class="gradeA">
                                         <td><input type="checkbox" data-form="uniform" name="inputCheckbox"></td>
                                         <td>Nokia N800</td>
                                         <td>N800</td>
                                         <td class="center">-</td>
                                         <td class="center">A</td>
                                     </tr>
                                     <tr class="gradeA">
                                         <td><input type="checkbox" data-form="uniform" name="inputCheckbox"></td>
                                         <td>Nintendo DS browser</td>
                                         <td>Nintendo DS</td>
                                         <td class="center">8.5</td>
                                         <td class="center">C/A<sup>1</sup></td>
                                     </tr>
                                     <tr class="gradeC">
                                         <td><input type="checkbox" data-form="uniform" name="inputCheckbox"></td>
                                         <td>Konqureror 3.1</td>
                                         <td>KDE 3.1</td>
                                         <td class="center">3.1</td>
                                         <td class="center">C</td>
                                     </tr>
                                     <tr class="gradeA">
                                         <td><input type="checkbox" data-form="uniform" name="inputCheckbox"></td>
                                         <td>Konqureror 3.3</td>
                                         <td>KDE 3.3</td>
                                         <td class="center">3.3</td>
                                         <td class="center">A</td>
                                     </tr>
                                     <tr class="gradeA">
                                         <td><input type="checkbox" data-form="uniform" name="inputCheckbox"></td>
                                         <td>Konqureror 3.5</td>
                                         <td>KDE 3.5</td>
                                         <td class="center">3.5</td>
                                         <td class="center">A</td>
                                     </tr>
                                 </tbody>
                             </table>

                         </div><!-- /box-body -->
                     </div><!-- /box -->
                 </div><!-- /span -->
             </div><!--/datatables tools-->
             <!--/tables-->
         </div><!--/content-body -->
     </div><!-- /content -->
 </div>
<!-- /span content -->