<!-- span content -->
<div class="span9">
    <!-- content -->
    <div class="content">
        <!-- content-header -->
        <div class="content-header">
            <!--ul class="content-header-action pull-right">
                <li>
                    <a href="#">
                        <span data-chart="peity-bar" data-height="32" data-colours='["#00A600", "#00A600"]'>5,3,9,6,5,9,7,3,5,2</span>
                        <div class="action-text color-green">8765 <span class="helper-font-small color-silver-dark">今日备忘</span></div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="#">
                        <span data-chart="peity-bar" data-height="32" data-colours='["#00A0B1", "#00A0B1"]'>9,7,9,6,3,5,3,5,5,2</span>
                        <div class="action-text color-teal">1437 <span class="helper-font-small color-silver-dark">今日邮件</span></div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="#">
                        <span data-chart="peity-bar" data-height="32" data-colours='["#BF1E4B", "#BF1E4B"]'>6,5,9,7,3,5,2,5,3,9</span>
                        <div class="action-text color-red">4367 <span class="helper-font-small color-silver-dark">今日审批</span></div>
                    </a>
                </li>
            </ul-->
            <h2><i class="icofont-home"></i> 主面板 <small>早安，招融文化</small></h2>
        </div><!-- /content-header -->

        <!-- content-breadcrumb -->
        <div class="content-breadcrumb">
            <!--breadcrumb-nav-->
            <!--ul class="breadcrumb-nav pull-right">
                <li class="divider"></li>
                <li class="btn-group">
                    <a href="#" class="btn btn-small btn-link dropdown-toggle" data-toggle="dropdown">
                        <i class="icofont-tasks"></i> 部门
                        <i class="icofont-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Some Action</a></li>
                        <li><a href="#">Other Action</a></li>
                        <li class="divider"></li>
                        <li><a href="#">Something Else</a></li>
                    </ul>
                </li>
                <li class="divider"></li>
                <li class="btn-group">
                    <a href="#" class="btn btn-small btn-link">
                        <i class="icofont-file"></i> 审批 <span class="color-red">(+12)</span>
                    </a>
                </li>
                <li class="divider"></li>
                <li class="btn-group">
                    <a href="#" class="btn btn-small btn-link">
                        <i class="icofont-user"></i> 在线人数 <span class="color-red">(+34)</span>
                    </a>
                </li>
            </ul--><!--/breadcrumb-nav-->

            <!--breadcrumb-->
            <ul class="breadcrumb">
                <li><a href="../system/dashboard"><i class="icofont-home"></i> 主面板</a> <span class="divider">&rsaquo;</span></li>
                <li class="active">概况</li>
            </ul><!--/breadcrumb-->
        </div><!-- /content-breadcrumb -->

        <!-- content-body -->
        <div class="content-body">
            <!-- dashboar -->
            <!-- shortcut button -->
            <div class="shortcut-group">
                <ul class="a-btn-group">
                    <li>
                        <a href="http://www.stone-soft.cn/attendance" class="a-btn grd-white" rel="tooltip" title="考勤维护">
                            <span></span>
                            <span><i class=" icofont-check color-silver-dark"></i></span>
                            <span class="color-silver-dark"><i class="icofont-check color-silver-dark"></i></span>
                        </a>
                    </li>
                    <li>
                        <a href="http://www.stone-soft.cn/approve/deal" class="a-btn grd-white" rel="tooltip" title="处理审批">
                            <span></span>
                            <span><i class=" icofont-briefcase color-silver-dark"></i></span>
                            <span class="color-silver-dark"><i class="icofont-briefcase color-silver-dark"></i></span>
                        </a>
                    </li>
                    <!--li>
                        <a href="#" class="a-btn grd-white" rel="tooltip" title="邮件">
                            <span></span>
                            <span><i class="icofont-envelope color-silver-dark"></i></span>
                            <span class="color-silver-dark"><i class="icofont-envelope-alt color-teal"></i></span>
                            <div class="badge badge-info">9</div> <!--don't use span here!-->
                        </a>
                    </li-->
                    <li>
                        <a href="http://www.stone-soft.cn/project/list" class="a-btn grd-white" rel="tooltip" title="我的项目">
                            <span></span>
                            <span><i class="icofont-ok-sign color-silver-dark"></i></span>
                            <span class="color-silver-dark"><i class="icofont-ok-sign color-red"></i></span>
                            <!--div class="label label-important">2</div--> <!--don't use span here!-->
                        </a>
                    </li>
                    <li>
                        <a href="http://www.stone-soft.cn/file/private" class="a-btn grd-white" rel="tooltip" title="我的网盘">
                            <span></span>
                            <span><i class="icofont-cloud color-silver-dark"></i></span>
                            <span class="color-silver-dark"><i class="icofont-cloud"></i></span>
                        </a>
                    </li>
                    <li class="clearfix"></li>
                </ul>
            </div><!-- /shortcut button -->

            <div class="divider-content"><span></span></div>

            <!-- tab stat -->
            <div class="box-tab corner-all">
                <div class="box-header corner-top">
                    <div class="header-control pull-right">
                        <a data-box="collapse"><i class="icofont-caret-up"></i></a>
                    </div>
                    <ul class="nav nav-tabs" id="tab-stat">
                        <!--li class="active"><a data-toggle="tab" href="#system-stat">项目状态</a></li-->
                        <li><a data-toggle="tab" href="#server-stat">系统状态</a></li>
                    </ul>
                </div>
                <div class="box-body">
                    <div class="tab-content">
                        <div class="tab-pane fade in active" id="system-stat" style="display:none;">
                            <div class="row-fluid">
                                <div class="span4">
                                    <div class="dashboard-stat">
                                        <div id="visitor-stat" class="chart" style="height: 120px;"></div>
                                        <div class="stat-label grd-green color-white">今日备忘</div>
                                    </div>
                                </div>
                                <div class="span4">
                                    <div class="dashboard-stat">
                                        <div id="order-stat" class="chart" style="height: 120px;"></div>
                                        <div class="stat-label grd-teal color-white">今日邮件</div>
                                    </div>
                                </div>
                                <div class="span4">
                                    <div class="dashboard-stat">
                                        <div id="user-stat" class="chart" style="height: 120px;"></div>
                                        <div class="stat-label grd-red color-white">今日审批</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="tab-pane fade in active" id="server-stat">
			    <div class="row-fluid">
				<div class="span4">
				    <div id="cpu" class="dashboard-stat" rel="tooltip">
					<input data-chart="knob" type="text" data-readonly="true" data-width="120" data-height="120" data-fgcolor="#00A600" value="" data-min="0" data-max="5000" />
					<div class="stat-label grd-green color-white">CPU</div>
				    </div>
				</div>
				<div class="span4">
				    <div id="memory" class="dashboard-stat" rel="tooltip">
					<input data-chart="knob" type="text" data-readonly="true" data-width="120" data-height="120" data-fgcolor="#00A0B1" value="" data-min="0" data-max="10000" />
					<div class="stat-label grd-teal color-white">内存</div>
				    </div>
				</div>
				<div class="span4">
				    <div id="disk" class="dashboard-stat" rel="tooltip">
					<input data-chart="knob" type="text" data-readonly="true" data-width="120" data-height="120" data-fgcolor="#AC193D" value="" data-min="0" data-max="100" />
					<div class="stat-label grd-red color-white">磁盘</div>
				    </div>
				</div>
			    </div>
			</div>
                    </div>
                </div>
            </div><!-- /tab stat -->

            <!-- tab resume content -->
            <div class="row-fluid">
                <!-- tab resume update -->
                <div class="span6">
                    <div class="box-tab corner-all">
                        <div class="box-header corner-top">
                            <!--tab action-->
                            <div class="header-control pull-right">
                                <a data-box="collapse"><i class="icofont-caret-up"></i></a>
                                <!--a data-box="close" data-hide="rotateOutDownLeft">&times;</a-->
                            </div>
                            <ul class="nav nav-pills">
                                <!--tab menus-->
                                <li class="active"><a data-toggle="tab" href="#recent-orders">最新公告</a></li>
                            </ul>
                        </div>
                        <div class="box-body">
                            <!-- widgets-tab-body -->
                            <div class="tab-content">
                                <div class="tab-pane fade in active" id="recent-orders">
				    <div node-id="notice_list">
					正在加载中。。。
				    </div>
                                    <a href="/notice/list" class="btn btn-small btn-link pull-right">查看所有 &rarr;</a>
                                </div>
                            </div><!--/widgets-tab-body-->
                        </div><!--/box-body-->
                    </div><!--/box-tab-->
                </div><!-- tab resume update -->
                <div class="span6">
                    <div class="box corner-all">
                        <div class="box-header corner-top grd-white">
                            <div class="header-control">
                                <a data-box="collapse"><i class="icofont-caret-up"></i></a>
                                <!--a data-box="close" data-hide="rotateOutDownRight">&times;</a-->
                            </div>
                            <span><i class="icofont-envelope"></i> 邮件</span>
                        </div>
                        <div class="box-body">
                            <form />
                                <div class="control-group">
                                    <label class="control-label">收件人：</label>
				    <style>
					.suggest{
						border:1px solid #ccc;
						line-height:30px;
						background-color: #ffffff;
						border: 1px solid #cccccc;
						-webkit-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075);
						-moz-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075);
						box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075);
						-webkit-transition: border linear 0.2s, box-shadow linear 0.2s;
						-moz-transition: border linear 0.2s, box-shadow linear 0.2s;
						-o-transition: border linear 0.2s, box-shadow linear 0.2s;
						transition: border linear 0.2s, box-shadow linear 0.2s;
						display: inline-block;
						padding: 4px 6px;
						margin-bottom: 10px;
						font-size: 14px;
						line-height: 20px;
						color: #555555;
						vertical-align: middle;
						-webkit-border-radius: 4px;
						-moz-border-radius: 4px;
						border-radius: 4px;
					}
					.suggest em{
						float: left;
						padding:0 3px;
						font-style:normal;
						font-size:12px;
						height:24px;
						line-height:24px;
					}
					.suggest em.select{
						background:#006b8e;
						color:#fff;
					}
					.suggest input{
						float: left;
						width:13px;
						border:none;
						height:24px;
						padding-bottom:0;
						padding-top:0;
						margin-bottom:0;
					}
				    </style>
                                    <div class="controls suggest input-block-level" id="js_reseiver">
                                        <input type="text" class="" name="reseiver" value="" />
					<ul>
					</ul>
                                    </div>
                                </div>
				<div class="control-group">
                                    <label class="control-label">抄送：</label>
                                    <div class="controls suggest input-block-level" id="js_ccreseiver">
                                        <input type="text" class="input-block-level" name="ccreseiver" value="" />
					<ul>
					</ul>
                                    </div>
                                </div>
                                <div class="control-group">
                                    <label class="control-label">主题：</label>
                                    <div class="controls">
                                        <input type="text" class="input-block-level grd-white" name="subject" />
                                    </div>
                                </div>
                                <div class="control-group">
                                    <label class="control-label">内容：</label>
                                    <div class="controls">
                                        <textarea name="message" data-form="wysihtml5" rows="6" class="span12"></textarea>
                                    </div>
				    <span class="help-inline" id="email_msg"></span>
                                </div>
                                <div class="form-actions">
                                    <input type="reset" class="btn" value="取消" />
                                    <input type="button" class="btn btn-primary" id="btn-send" value="发送" />
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div><!-- tab stat -->

            <!--schedule-->
            <div class="box corner-all">
                <div class="box-header grd-white color-silver-dark corner-top">
                    <div class="header-control">
                        <a data-box="collapse"><i class="icofont-caret-up"></i></a>
                    </div>
                    <span>备忘录</span>
                </div>
                <div class="box-body">
                    <div id="calendar"></div>
                </div>
            </div>
            <!--schedule-->

            <!--/dashboar-->
        </div><!--/content-body -->
    </div><!-- /content -->
</div>
<!-- /span content -->