<!-- span content -->
<div class="span9">
    <!-- content -->
    <div class="content">
       

        <!-- content-breadcrumb -->
        <div class="content-breadcrumb">
            

            <!--breadcrumb-->
            <ul class="breadcrumb">
                <li><a href="index.html"><i class="icofont-home"></i> 主板面</a> <span class="divider">&rsaquo;</span></li>
                <li class="active">考勤管理</li>
            </ul><!--/breadcrumb-->
        </div><!-- /content-breadcrumb -->

        <!-- content-body -->
        <div class="content-body">
            <!-- calendar -->
            <div class="row-fluid">
                <div class="span9">
                    <div class="box corner-all">
                        <div class="box-header grd-white corner-top">
                            <span>备忘录</span>
                        </div>
                        <div class="box-body">
                            <div id="calendar"></div>
                        </div>
                    </div>
                </div>
                <div class="span3">
                    <div class="box corner-all">
                        <div class="box-header grd-white corner-top">
                            <span>Event</span>
                        </div>
                        <div class="box-body">
                            <div class='external-event label label-warning' style="display: block;padding: 5px;margin-bottom: 10px">My Event 1</div>
                            <div class='external-event label label-warning' style="display: block;padding: 5px;margin-bottom: 10px">My Event 2</div>
                            <div class='external-event label label-warning' style="display: block;padding: 5px;margin-bottom: 10px">My Event 3</div>
                            <div class='external-event label label-warning' style="display: block;padding: 5px;margin-bottom: 10px">My Event 4</div>
                            <div class='external-event label label-warning' style="display: block;padding: 5px;margin-bottom: 10px">My Event 5</div>
                            <label for='drop-remove'><input type='checkbox' data-form="uniform" id='drop-remove' /> <small class="helper-font-small">remove after drop</small></label>
                        </div>
                    </div>
                </div>
            </div>
            <!--/calendar-->
        </div><!--/content-body -->
    </div><!-- /content -->
</div>
<!-- /span content -->
                
 