<!-- span content -->
<div class="span9">
    <!-- content -->
    <div class="content">
        <!-- content-header 
        <div class="content-header">
            <ul class="content-header-action pull-right">
                <li>
                    <a href="#">
                        <span data-chart="peity-bar" data-height="32" data-colours='["#00A600", "#00A600"]'>5,3,9,6,5,9,7,3,5,2</span>
                        <div class="action-text color-green">8765 <span class="helper-font-small color-silver-dark">今日备忘</span></div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="#">
                        <span data-chart="peity-bar" data-height="32" data-colours='["#00A0B1", "#00A0B1"]'>9,7,9,6,3,5,3,5,5,2</span>
                        <div class="action-text color-teal">1437 <span class="helper-font-small color-silver-dark">今日邮件</span></div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="#">
                        <span data-chart="peity-bar" data-height="32" data-colours='["#BF1E4B", "#BF1E4B"]'>6,5,9,7,3,5,2,5,3,9</span>
                        <div class="action-text color-red">4367 <span class="helper-font-small color-silver-dark">今日审批</span></div>
                    </a>
                </li>
            </ul>
            <h2><i class="icofont-home"></i> 主面板 <small>早安，招融文化</small></h2>
        </div> /content-header -->

        <!-- content-breadcrumb -->
        <div class="content-breadcrumb">
            <!--breadcrumb-nav
            <ul class="breadcrumb-nav pull-right">
                <li class="divider"></li>
                <li class="btn-group">
                    <a href="#" class="btn btn-small btn-link">
                        <i class="icofont-user"></i> New User
                    </a>
                </li>
                <li class="divider"></li>
                <li class="btn-group">
                    <a href="#" class="btn btn-small btn-link dropdown-toggle" data-toggle="dropdown">
                        <i class="icofont-cogs"></i> Actions
                        <i class="icofont-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="#" class="all-message">All Message</a></li>
                        <li><a href="#" class="read-message">Read Message</a></li>
                        <li><a href="#" class="unread-message">Unread Message</a></li>
                        <li class="divider"></li>
                        <li><a href="#" class="select-all">Select All</a></li>
                        <li><a href="#" class="unselect-all">Unselect All</a></li>
                        <li class="divider"></li>
                        <li><a href="#" class="get-selected">Get Selected</a></li>
                        <li><a href="#" class="delete-message">Delete Message</a></li>
                        <li class="divider"></li>
                        <li><a href="#">Something Else</a></li>
                    </ul>
                </li>
                <li class="divider"></li>
                <li class="btn-group">
                    <a href="#" class="btn btn-small btn-link">
                        <i class="icofont-fire"></i> Other Action
                    </a>
                </li>
            </ul>/breadcrumb-nav-->

            <!--breadcrumb-->
            <ul class="breadcrumb">
                <li><a href="../system/dashboard"><i class="icofont-home"></i>主面板</a> <span class="divider">&rsaquo;</span></li>
                <li class="active">消息</li>
            </ul><!--/breadcrumb-->
        </div><!-- /content-breadcrumb -->

        <!-- content-body -->
        <div class="content-body">
            <!-- message -->
            <!-- message-a -->
	    
            <!-- toolbar controller -->
            <!--<div id="toolbar-control" class="message-control btn-toolbar pull-right">
                <div class="btn-group">
                    <a href="#new-message" class="btn btn-small" data-toggle="tab"><i class="icofont-edit"></i> New Message</a>
                    <a href="#" class="btn btn-small" data-toggle="tab"><i class="icofont-hdd"></i> Archives</a>
                    <a href="#" class="btn btn-small" data-toggle="tab"><i class="icofont-star-empty"></i> Other</a>
                </div>
                <div class="btn-group">
                    <a href="#" class="btn btn-small dropdown-toggle" data-toggle="dropdown">
                        <i class="icofont-cogs"></i> Actions
                        <i class="icofont-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu helper-font-small">
                        <li><a href="#" class="all-message">All Message</a></li>
                        <li><a href="#" class="read-message">Read Message</a></li>
                        <li><a href="#" class="unread-message">Unread Message</a></li>
                        <li class="divider"></li>
                        <li><a href="#" class="select-all">Select All</a></li>
                        <li><a href="#" class="unselect-all">Unselect All</a></li>
                        <li class="divider"></li>
                        <li><a href="#" class="get-selected">Get Selected</a></li>
                        <li><a href="#" class="delete-message">Delete Message</a></li>
                        <li class="divider"></li>
                        <li><a href="#">Something Else</a></li>
                    </ul>
                </div>
            </div>--><!-- toolbar controller -->

            <div class="message-a">
                <!-- message contact, this on left side -->
                <div class="message-contact">
                    <!-- message contact header -->
                    <div class="mc-header">
                        <div class="input-icon-prepend">
                            <span class="icon"><i class="icofont-search"></i></span>
                            <input id="search-contact" type="text" class="input-block-level" placeholder="搜索联系人" />
                        </div>
                    </div><!-- /message contact header -->
                    <!-- message contact content -->
                    <div class="mc-content">
                        <!-- list content -->
                        <ul class="contact-list" id="full-contact-list">
                        </ul><!-- /list contact -->
                    </div><!-- /message contact content -->
                </div><!-- /message contact-->

                <!-- message body, this on right side -->
                <div class="message-body">
                    <div class="mb-content">
                        <div>
                            <!--new message-->
                            <div class="tab-pane">
                                <div class="new-message">
                                    <div class="msg-new-head">
                                        <label class="control-label help-inline" id="chat_to_name">To: </label>
                                        <input type="hidden" style="width:70%" name="receiver" data-form="select2" value="janesmith" />
                                    </div>
				    <div class="tab-content chat-content">
				    </div>
                                    <!--status typed part-->
                                    <!--div class="msg-typed"><i class="typicn-chat"></i> </div-->
                                </div>
                            </div><!--new message-->
                        </div>

                        <!--input part-->
                        <div class="msg-input">
                            <form enctype="multipart/form-data" />
                                <div class="msg-desc muted">Lorem ipsum dolor sit amet.</div>
                                <textarea name="message-writer" class="input-block-level" placeholder=""></textarea>
                                <div class="">
                                    <label class="checkbox helper-font-small">
                                        <input type="checkbox" data-form="uniform" id="sendEnter" name="sendEnter" checked="" />按下回车键发送
                                    </label>
                                </div>
                                <!--this upload button, we improve it with jquery, see js code below-->
                                <!--input data-form="upload-helper" type="file" name="attach-file" />
                                <button data-form="upload-helper" data-target="attach-file" class="btn btn-small btn-link"><i class="icofont-paper-clip"></i> attach file</button>

                                <input data-form="upload-helper" type="file" name="attach-alt" />
                                <button data-form="upload-helper" data-target="attach-alt" class="btn btn-small btn-link"><i class="icofont-upload-alt"></i> add something</button-->
                            </form>
                        </div><!--/input part-->
                    </div>
                </div>
            </div>
            <!--/message-->
        </div><!--/content-body -->
    </div><!-- /content -->
</div>
<!-- /span content -->