<!-- span content -->
<div class="span9">
    <!-- content -->
    <div class="content">
        <!-- content-breadcrumb -->
        <div class="content-breadcrumb">                            
            <!--breadcrumb-->
            <ul class="breadcrumb">
                <li><a href="../system/dashboard"><i class="icofont-home"></i>主面板</a> <span class="divider">&rsaquo;</span></li>
                <li><a href="list">公告管理</a> <span class="divider">&rsaquo;</span></li>
                <li class="active">我的公告</li>
            </ul><!--/breadcrumb-->
        </div><!-- /content-breadcrumb -->
        <!-- content-body -->
        <div class="content-body">
            <!-- tables -->
            <!--datatables-->
            <div class="row-fluid">
                <div class="span12">
                    <div class="box corner-all">
                        <div class="box-header grd-white corner-top">
                            <!--div class="header-control">
                                <a data-box="collapse"><i class="icofont-caret-up"></i></a>
                                <a data-box="close" data-hide="bounceOutRight">&times;</a>
                            </div-->
                            <span>我的公告</span>
                        </div>
                        <div class="box-body">
                            <table id="annlist" class="table table-bordered table-striped responsive">
                                <thead>
                                    <tr>
                                        <th>公告名称</th>
                                        <th>描述</th>
                                        <th>状态</th>
                                        <th>操作</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php foreach ($announceList as $index => $announce):?>
					<tr><td><?=$announce["title"]?></td><td><?=$announce["content"]?></td><td><?php if($announce["ann_type"] == 0){echo "普通";}else{ echo "重要";}?></td><td><a class="btn btn-small" title="编辑" href='/notice/set/id/<?=$announce["id"]?>'><i class="icofont-edit"></i></a><a class="btn btn-small" title="删除" act="del" did='<?=$announce["id"]?>'><i class="icofont-remove-sign"></i></a></td></tr>
				    <?php endforeach;?>
                                </tbody>
                            </table>

                        </div><!-- /box-body -->
                    </div><!-- /box -->
                </div><!-- /span -->
            </div><!--/datatables-->
            <!--/tables-->
        </div><!--/content-body -->
    </div><!-- /content -->
</div>
<!-- /span content -->