<!-- span content -->
<div class="span9">
    <!-- content -->
    <div class="content">
        <!-- content-breadcrumb -->
        <div class="content-breadcrumb">                            
            <!--breadcrumb-->
            <ul class="breadcrumb">
                <li><a href="../system/dashboard"><i class="icofont-home"></i>主面板</a> <span class="divider">&rsaquo;</span></li>
                <li><a href="list">项目管理</a> <span class="divider">&rsaquo;</span></li>
                <li class="active">我的项目</li>
            </ul><!--/breadcrumb-->
        </div><!-- /content-breadcrumb -->
        <!-- content-body -->
        <div class="content-body">
            <!-- tables -->
            <!--datatables-->
            <div class="row-fluid">
                <div class="span12">
                    <div class="box corner-all">
                        <div class="box-header grd-white corner-top">
                            <!--div class="header-control">
                                <a data-box="collapse"><i class="icofont-caret-up"></i></a>
                                <a data-box="close" data-hide="bounceOutRight">&times;</a>
                            </div-->
                            <span>我的项目</span>
                        </div>
			<style>
				.probar{
				   
				}
				.probar p{
				   margin-left:10px;
				   overflow:visible;
				}
				.probar .ui-slider-range-max{
				   
				}
				.probar .ui-slider-handle{
				
				}
				.probar span{
					position:absolute;
					left: 50%;
					margin-left:20px;
				}
			</style>
                        <div class="box-body">
                            <table id="datatables" class="table table-bordered table-striped responsive">
					<thead>
						<tr>
							<th class='span3'>项目名称</th>
							<th class='span3'>负责人</th>
							<th class='span3'>状态</th>
							<th>进度</th>
						</tr>
					</thead>
					<tbody>
						<!--<tr class="odd">
							<td class=" sorting_1"><a href="/project/detail#17">asdf</a></td>
							<td class=" ">a</td>
							<td class=" ">2个月</td>
							<td class="probar ">
								<p><span></span>100%</p>
							</td>
						</tr>
						<tr class="even">
							<td class=" sorting_1"><a href="/project/detail#68">adfadf</a></td>
							<td class=" ">adsf</td>
							<td class=" ">3周</td>
							<td class="probar ">
								<p class='finsh'><span></span>100%</p>
								
							</td>
						</tr>
						<tr class="odd">
							<td class=" sorting_1"><a href="/project/detail#17">adf</a></td>
							<td class=" ">b</td>
							<td class=" ">1个月4天</td>
							<td class="probar ">
								<p class='delay'><span></span>100%</p>
							</td>
						</tr>-->
					</tbody>
				</table>

                        </div><!-- /box-body -->
                    </div><!-- /box -->
                </div><!-- /span -->
            </div><!--/datatables-->
            <!--/tables-->
        </div><!--/content-body -->
    </div><!-- /content -->
</div>
<!-- /span content -->

<div class="pro-layer" style='left:900px;top:295px;display:none;'>
	<span class="arrow"></span>
	<p>起始时间：2014年09月02日</p>
	<p>结束时间：2014年09月12日</p>
	<p>状态：1个月</p>
	<p>进度：95%</p>
	<p>超出/结余：2天</p>
</div>
