<!-- span content -->
<div class="span9">
    <!-- content -->
    <div class="content">
        <!-- content-breadcrumb -->
        <div class="content-breadcrumb">                            
            <!--breadcrumb-->
            <ul class="breadcrumb">
                <li><a href="../system/dashboard"><i class="icofont-home"></i>主面板</a> <span class="divider">&rsaquo;</span></li>
                <li><a href="list">项目管理</a> <span class="divider">&rsaquo;</span></li>
                <li class="active">我的项目</li>
            </ul><!--/breadcrumb-->
        </div><!-- /content-breadcrumb -->
        <!-- content-body -->
        <div class="content-body">
            <!-- tables -->
            <!--datatables-->
            <div class="row-fluid">
                <div class="span12">
                    <div class="box corner-all">
                        <div class="box-header grd-white corner-top">
                            <!--div class="header-control">
                                <a data-box="collapse"><i class="icofont-caret-up"></i></a>
                                <a data-box="close" data-hide="bounceOutRight">&times;</a>
                            </div-->
                            <span>我的项目</span>
                        </div>
                        <div class="box-body">
                            <table id="datatables" class="table table-bordered table-striped responsive">
                                <thead>
                                    <tr>
                                        <th>项目名称</th>
                                        <th>负责人</th>
                                        <th>状态</th>
                                        <th>开始时间</th>
                                        <th>更新时间</th>
                                    </tr>
                                </thead>
                                <tbody>
				   
                                </tbody>
                            </table>

                        </div><!-- /box-body -->
                    </div><!-- /box -->
                </div><!-- /span -->
            </div><!--/datatables-->
            <!--/tables-->
        </div><!--/content-body -->
    </div><!-- /content -->
</div>
<!-- /span content -->
               