<!-- span content -->
<div class="span9">
    <!-- content -->
    <div class="content">
        <!-- content-header 
        <div class="content-header">
            <ul class="content-header-action pull-right">
                <li>
                    <a href="#">
                        <div class="badge-circle grd-green color-white"><i class="icofont-plus-sign"></i></div>
                        <div class="action-text color-green">8765 <span class="helper-font-small color-silver-dark">Visits</span></div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="#">
                        <div class="badge-circle grd-teal color-white"><i class="icofont-user-md"></i></div>
                        <div class="action-text color-teal">1437 <span class="helper-font-small color-silver-dark">Users</span></div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="#">
                        <div class="badge-circle grd-orange color-white">$</div>
                        <div class="action-text color-orange">4367 <span class="helper-font-small color-silver-dark">Orders</span></div>
                    </a>
                </li>
            </ul>
            <h2><i class="icofont-file"></i> Form Elements</h2>
        </div> /content-header -->

        <!-- content-breadcrumb -->
        <div class="content-breadcrumb">
            <!--breadcrumb-nav
            <ul class="breadcrumb-nav pull-right">
                <li class="divider"></li>
                <li class="btn-group">
                    <a href="#" class="btn btn-small btn-link dropdown-toggle" data-toggle="dropdown">
                        <i class="icofont-cogs"></i> Controls
                        <i class="icofont-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="#element" class="scroll">Element</a></li>
                        <li><a href="#validation" class="scroll">Validation</a></li>
                        <li><a href="#wizard" class="scroll">Wizard</a></li>
                        <li class="divider"></li>
                        <li><a href="#extending" class="scroll">Extending</a></li>
                        <li><a href="#controls" class="scroll">Controls</a></li>
                        <li class="divider"></li>
                        <li><a href="#buttons" class="scroll">Buttons</a></li>
                    </ul>
                </li>
                <li class="divider"></li>
                <li class="btn-group">
                    <a href="#" class="btn btn-small btn-link">
                        <i class="icofont-user"></i> Users <span class="color-red">(+34)</span>
                    </a>
                </li>
            </ul>/breadcrumb-nav-->

            <!--breadcrumb-->
            <ul class="breadcrumb">
                <li><a href="../system/dashboard"><i class="icofont-home"></i>主面板</a> <span class="divider">&rsaquo;</span></li>
                <li><a href="list">项目管理</a> <span class="divider">&rsaquo;</span></li>
                <li class="active">新建项目</li>
            </ul><!--/breadcrumb-->
        </div><!-- /content-breadcrumb -->

        <!-- content-body -->
        <div class="content-body">
            <!-- form -->
            <div class="row-fluid">
                <div class="span12">

                    <!-- =========================================
                                        ELEMENT
                    =========================================== -->
                    <!--element-->
                    <div id="element" class="row-fluid">
                        <!--span-->
                        <div class="span12">
                            <!--box-->
                            <div class="box corner-all">
                                <!--box header-->
                                <div class="box-header grd-white color-silver-dark corner-top">
                                    <!--div class="header-control">
                                        <a data-box="collapse"><i class="icofont-caret-up"></i></a>
                                        <a data-box="close">&times;</a>
                                    </div-->
                                    <span>新建项目</span>
                                </div><!--/box header-->
                                <!--box body-->
                                <div class="box-body">
                                    <!--element-->
                                    <form class="form-horizontal" action="" >
					<div class="control-group">
                                            <label class="control-label" for="inputAuto">*项目名称</label>
                                            <div class="controls">
                                                <input type="text" class="grd-white" name="name" id="pro_name"/>
                                            </div>
                                        </div>
					<div id="approve-steps">
						<div class="control-group">
						    <label class="control-label" for="inputSelectMulti">项目成员</label>
						    <div class="controls">
							<select  id="pro_group" name="approver" data-form="select2" style="width:220px"  multiple="">

							</select>
							
						    </div>
						</div> 
						<!--div class="control-group">
						    <label class="control-label" for="inputSelectMulti">权限</label>
						    <div class="controls">
							<label class="checkbox">
							    <input type="checkbox" data-form="uniform" name="stependable" value="1" />成员只能查阅自己参与的任务
							</label>
						    </div>
						</div-->
					</div>
					<div class="control-group">
					    <label class="control-label" for="inputDate">开始时间</label>
					    <div class="controls">
						<div class="input-append date" data-form="datepicker" data-date="2014-04-01" data-date-format="yyyy-mm-dd">
						    <input name="start_date" class="grd-white"  size="16" type="text" readonly="true"/>
						    <span class="add-on"><i class="icon-th"></i></span>
						</div>
					    </div>
					</div>
					<div class="control-group">
					    <label class="control-label" for="inputDate">结束时间</label>
					    <div class="controls">
						<div class="input-append date" data-form="datepicker" data-date="2014-04-01" data-date-format="yyyy-mm-dd">
						    <input name="end_date" class="grd-white"  size="16" type="text" readonly="true"/>
						    <span class="add-on"><i class="icon-th"></i></span>
						</div>
					    </div>
					</div>
					<div class="control-group">
                                            <label class="control-label" for="inputAuto">进度</label>
                                            <div class="controls">
                                                <input type="number" class="grd-white" name="name" min="0" max="100"  id="process"/>%
                                            </div>
                                        </div>
					<div class="control-group">
					    <label class="control-label" for="inputDate">项目状态</label>
					    <div class="controls">
						<input type="text" class="grd-white" name="name" min="0" max="100"  id="project_status"/>
					    </div>
					</div>
					<div class="control-group">						
					    <div class="controls">
						<button id="btn-create" type="button" class="btn btn-primary">确定</button>
					    </div>
					</div> 
                                    </form>
                                    <!--/element-->
                                </div><!--/box body-->
                            </div><!--/box-->
                        </div><!--/span--> 
                    </div><!--/element-->

                </div><!--/span-->
            </div><!--/row-fluid-->
            <!--/form-->
        </div><!--/content-body -->
    </div><!-- /content -->
</div>
<!-- /span content -->
