<!-- span content -->
<div class="span9">
    <!-- content -->
    <div class="content">
        <!-- content-header 
        <div class="content-header">
            <ul class="content-header-action pull-right">
                <li>
                    <a href="#">
                        <div class="badge-circle grd-green color-white"><i class="icofont-plus-sign"></i></div>
                        <div class="action-text color-green">8765 <span class="helper-font-small color-silver-dark">Visits</span></div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="#">
                        <div class="badge-circle grd-teal color-white"><i class="icofont-user-md"></i></div>
                        <div class="action-text color-teal">1437 <span class="helper-font-small color-silver-dark">Users</span></div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="#">
                        <div class="badge-circle grd-orange color-white">$</div>
                        <div class="action-text color-orange">4367 <span class="helper-font-small color-silver-dark">Orders</span></div>
                    </a>
                </li>
            </ul>
            <h2><i class="icofont-file"></i> Form Elements</h2>
        </div> /content-header -->

        <!-- content-breadcrumb -->
        <div class="content-breadcrumb">
            <!--breadcrumb-nav
            <ul class="breadcrumb-nav pull-right">
                <li class="divider"></li>
                <li class="btn-group">
                    <a href="#" class="btn btn-small btn-link dropdown-toggle" data-toggle="dropdown">
                        <i class="icofont-cogs"></i> Controls
                        <i class="icofont-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="#element" class="scroll">Element</a></li>
                        <li><a href="#validation" class="scroll">Validation</a></li>
                        <li><a href="#wizard" class="scroll">Wizard</a></li>
                        <li class="divider"></li>
                        <li><a href="#extending" class="scroll">Extending</a></li>
                        <li><a href="#controls" class="scroll">Controls</a></li>
                        <li class="divider"></li>
                        <li><a href="#buttons" class="scroll">Buttons</a></li>
                    </ul>
                </li>
                <li class="divider"></li>
                <li class="btn-group">
                    <a href="#" class="btn btn-small btn-link">
                        <i class="icofont-user"></i> Users <span class="color-red">(+34)</span>
                    </a>
                </li>
            </ul>/breadcrumb-nav-->

            <!--breadcrumb-->
            <ul class="breadcrumb">
                <li><a href="../system/dashboard"><i class="icofont-home"></i>主面板</a> <span class="divider">&rsaquo;</span></li>
                <li><a href="list">项目管理</a> <span class="divider">&rsaquo;</span></li>
		<li><a href="detail">项目进度</a> <span class="divider">&rsaquo;</span></li>
                <li class="active">任务详情</li>
            </ul><!--/breadcrumb-->
        </div><!-- /content-breadcrumb -->

        <!-- content-body -->
	<script>
		var projectid = '<?=$task["project_id"]?>',
		    taskid = '<?=$task["id"]?>';
	</script>
        <div class="content-body">
            <!-- form -->
            <div class="row-fluid">
                <div class="span12">

                    <!-- =========================================
                                        ELEMENT
                    =========================================== -->
                    <!--element-->
                    <div id="element" class="row-fluid">
                        <!--span-->
                        <div class="span12">
                            <!--box-->
                            <div class="box corner-all">
                                <!--box header-->
                                <div class="box-header grd-white color-silver-dark corner-top">
                                    <!--div class="header-control">
                                        <a data-box="collapse"><i class="icofont-caret-up"></i></a>
                                        <a data-box="close">&times;</a>
                                    </div-->
                                    <span>项目进度</span>
                                </div><!--/box header-->
                                <!--box body-->
                                <div class="box-body">
                                    <!--element-->
						<a class="btn" href="/project/detail#<?=$task["project_id"]?>" style="margin-bottom:10px;"  id="btn-addlandmark">返回</a>
					    <!-- invoice -->
					    <div id="invoice-container" class="invoice-container">
						<div class="page-header">
						    <h4><?=$task["title"]?></h4>
						</div>
						<div class="row-fluid">
						    <div class="span10">
							<p>负责人：<?=$task['manager']?></p>
							<p class="">结束时间：<?=$task["end_date"]?></p>
							<p>里程碑：无</p>
							<p>正文：<?=$task["description"]?></p>
						    </div>
						</div>
						<div class="box-body">
							<h4>附件</h4>
							<a class="btn" style="margin-bottom:10px;position:relative;overflow:hidden;"  id="btn-addlandmark"><span>上传文件</span><input type="file" class="input-upload" id="addtaskfile"  multiple="multiple"/></a>
						    <table id="taskfiles_list" class="table table-bordered table-striped responsive mail">
							 <thead>
							     <tr>
								 <th>文件名</th>
								 <th>上传时间</th>
							     </tr>
							 </thead>
							 <tbody>
							     
							 </tbody>
						     </table>
						</div>

						<!--div class="box-body">
							<h4>动态</h4>
						    <table id="datatables" class="table table-bordered table-striped responsive mail">
							 <thead>
							     <tr>
								 <th>用户</th>
								 <th>动作</th>
								 <th>开始时间</th>
								 <th>结束时间</th>
								 <th>备注</th>
							     </tr>
							 </thead>
							 <tbody>
							     <tr class="odd gradeX">
								 <td class="center">yuanxu</td>
								 <td>新建任务</td>
								 <td class="center">2014-04-02 17:52:00</td>
								 <td class="center">2014-04-02 17:52:00</td>
								 <td class="center">adsfaf</td>
							     </tr>
							     <tr class="odd gradeX">
								 <td class="center">yuanxu</td>
								 <td>上传文件<a href="#">stone.psd</a></td>
								 <td class="center">2014-04-02 17:52:00</td>
								 <td class="center">2014-04-02 17:52:00</td>
								 <td class="center">v2.0</td>
							     </tr>
							 </tbody>
						     </table>
						</div-->
					    </div>
					    <!--/invoice-->
					

                                    <!--/element-->
                                </div><!--/box body-->
                            </div><!--/box-->
                        </div><!--/span--> 
                    </div><!--/element-->

                </div><!--/span-->
            </div><!--/row-fluid-->
            <!--/form-->
        </div><!--/content-body -->
    </div><!-- /content -->
</div>
<!-- /span content -->
